scaleway/scaleway-cli

.pkgr.yml
I saw you tried packaging on https://packager.io, but were missing the [`.godir` file](https://packager.io/documentation/golang/). So here is a working `.pkgr.yml` file for some of the supported distributions.
Packages can be found at https://packager.io/gh/pkgr/scaleway-cli/install?bid=2#ubuntu-14-04-scw, and I verified that you can install and run the `scw` command on Ubuntu 14.04, so it should work on the other distributions as well.
Let me know if this is of interest to you! We can also provide a standalone server so that you can serve the generated packages from your own domain and servers.
=> Enable packaging with https://packager.io

.pkgr.yml
Since you've created a proper `.godir` already, let's use that (successful build available at https://packager.io/gh/pkgr/scaleway-cli/build_runs/5),
=> Remove .godir generation from .pkgr.yml

.pkgr.yml
Now that the `.godir` uses `scaleway-cli` as the binary name, we need to rename it at the end of the compilation so that one can successfully run `scw` after the package is installed.
=> Rename scaleway-cli into scw at the end of packaging

Makefile, api/helpers.go, commands/events.go
api/helpers.go:145: possible formatting directive in Fprint call
commands/events.go:59: arg event.Progress for printf verb %s of wrong type: int
vendor/code.google.com/p/go-uuid/uuid/uuid.go:116: unreachable code
vendor/code.google.com/p/go-uuid/uuid/uuid_test.go:319: no formatting directive in Errorf call
vendor/code.google.com/p/go-uuid/uuid/uuid_test.go:328: no formatting directive in Errorf call
vendor/code.google.com/p/go-uuid/uuid/uuid_test.go:331: no formatting directive in Errorf call
vendor/golang.org/x/crypto/ssh/terminal/terminal.go:744: unreachable code
=> fix suspicious errors and adding go tool vet

README.md, pkg/api/api.go, pkg/cli/x_patch.go
i.e: `scw _patch server:bitrig-build tags="test test=test toto=titi tutu"`
=> Support of 'scw _patch SERVER tags="tag1 tag2 tag3"'

README.md, pkg/api/api.go, pkg/cli/x_patch.go, pkg/sshcommand/sshcommand.go, vendor/github.com/moul/http2curl/LICENSE, vendor/github.com/moul/http2curl/Makefile, vendor/github.com/moul/http2curl/README.md, vendor/github.com/moul/http2curl/http2curl.go, vendor/github.com/moul/http2curl/http2curl_test.go
```console
$ scw -D inspect server:alpine | anonuuid
DEBU[0000] curl -X GET -H "X-Auth-Token: 00000000-0000-0000-0000-000000000000" -H "Content-Type: application/json" https://api.scaleway.com/servers/4275e304-9b40-4c1b-9baf-36e888721c1e
[{
"id": "00000000-0000-1000-0000-000000000000",
"name": "[rescue] distrib-alpine-latest",
"creation_date": "2015-03-18T10:01:42.761470+00:00",
...
```
```console
$ scw -D create alpine
DEBU[0000] curl -X POST -d "{\"name\":\"focused-morse\",\"image\":\"00000000-0000-1000-0000-000000000000\",\"dynamic_ip_required\":true,\"bootscript\":null,\"organization\":\"11111111-1111-1111-1111-111111111111\"}" -H "X-Auth-Token: 00000000-0000-0000-0000-000000000000" -H "Content-Type: application/json" https://api.scaleway.com/servers
DEBU[0001] curl -X GET -H …
```
=> Printing `curl` commands when debugging API requests

pkg/api/helpers.go
I triggered this with:
$ scw wait abcdef
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x52137e]
goroutine 1 [running]:
github.com/scaleway/scaleway-cli/pkg/api.WaitForServerState(0xc820086580, 0xc8203e4c90, 0x24, 0x8993b8, 0x7, 0x0, 0x0, 0x0)
go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:392 +0x30e
github.com/scaleway/scaleway-cli/pkg/api.WaitForServerStopped(0xc820086580, 0xc8203e4c90, 0x24, 0xc8203e4c90, 0x0, 0x0)
go/src/github.com/scaleway/scaleway-cli/pkg/api/helpers.go:468 +0x5a
github.com/scaleway/scaleway-cli/pkg/commands.RunWait(0x7f6afb1eb220, 0xc82002a008, 0x7f6afb1eb308, 0xc82002a010, 0x7f6afb1eb308, 0xc82002a018, 0xc82000cc80, 0x28, 0x28, 0xc82000a2f0, ...) …
=> Fix nil pointer dereference

pkg/commands/info.go, pkg/utils/utils.go
=> fix 130 add infos

Makefile, README.md, pkg/cli/commands.go, pkg/cli/test.go, pkg/cli/x_billing.go, pkg/pricing/basket.go, pkg/pricing/basket_test.go, pkg/pricing/pricing.go, pkg/pricing/pricing_test.go, pkg/pricing/usage.go, pkg/pricing/usage_test.go, pkg/pricing/utils.go, pkg/pricing/utils_test.go
This is the initial version of billing, it's not yet complete and result is approximative but already useful, and this is a good start to iterate over new features and improvements in the future
=> Feature billing

README.md, examples/create-image-from-http.sh, pkg/api/api.go, pkg/cli/cmd_tag.go, pkg/commands/tag.go
=> Update and rename create-image-from-s3.sh to create-image-from-http.sh

README.md, pkg/api/api.go, pkg/cli/commands.go, pkg/cli/x_patch.go, pkg/cli/x_security-groups.go
#179 
Get security-groups
```bash
$> ./scw _security-groups  | jq . | anonuuid
{
"security_groups": [
{
"description": "Auto generated security group.",
"enable_default_security": false,
"id": "00000000-0000-1000-0000-000000000000",
"organization": "11111111-1111-1111-1111-111111111111",
"name": "Default security group",
"organization_default": true,
"servers": [
{
"id": "22222222-2222-1222-2222-222222222222",
"name": "loving-wilson"
}
]
},
{
"description": "toto",
"enable_default_security": true,
"id": "bbbbbbbb-bbbb-1bbb-bbbb-bbbbbbbbbbbb",
"organization": "11111111-1111-1111-1111-111111111111",
"name": "toto",
"organization_default": false,
"servers": []
}
]
}
```
Get a specific security group
```bash
$> ./scw _security-groups "00000000-0000-1000-0000-000000000000"  | jq . | anonuuid
{ …
```
=> adds _security-groups

pkg/api/cache.go
`os.Rename` only works if src and dest are on the same partition. So if `$TMPDIR`
and `$HOME` are on different paritions the cache file was never written and a lot
of temp files were left behind.
=> Various cache file handling fixes

README.md, pkg/api/api.go, pkg/commands/info.go
=> Added permissions `scw info`

README.md, pkg/api/api.go, pkg/cli/commands.go
#178 
Display the IPs
```bash
./scw _ips | anonuuid
{
"ips": [
{
"organization": "00000000-0000-1000-0000-000000000000",
"reverse": "",
"id": "11111111-1111-1111-1111-111111111111",
"server": {
"id": "22222222-2222-1222-2222-222222222222",
"name": "buildwordpress"
},
"address": "212.47.239.7"
}
]
}
```
Display an IP
```bash
./scw _ips 11111111-1111-1111-1111-111111111111 | anonuuid
{
"ip": {
"organization": "00000000-0000-1000-0000-000000000000",
"reverse": "",
"id": "11111111-1111-1111-1111-111111111111",
"server": {
"id": "22222222-2222-1222-2222-222222222222",
"name": "buildwordpress"
},
"address": "212.47.239.7"
}
}
```
New IP
```bash
./scw _ips -n
{
"ip": {
"organization": "00000000-0000-1000-0000-000000000000",
"reverse": "",
"id": "11111111-1111-1111-1111-111111111111",
"server": …
```
=> Added _ips

pkg/api/helpers.go
The code should catch when the server is already started and you try
to call "scw start <id>" but currently that doesn't happen due to a
typo s/!=/==/.
=> Fix bug that starting an already started server succeeds.

README.md, pkg/utils/utils.go
#160
:warning: Don't merge yet :warning:
=> Use gotty-client instead of termjs-cli

README.md, pkg/cli/cmd_run.go, pkg/commands/attach.go, pkg/commands/run.go, pkg/utils/utils.go, vendor/github.com/moul/gotty-client/README.md, vendor/github.com/moul/gotty-client/gotty-client.go
=> Support scw run --show-boot

goversion.go, goversion_unsupported.go
```console
root@733000e59cca:~/bin# eval "$(GIMME_GO_VERSION=1.1 ./gimme)"
go version go1.1 linux/amd64
root@733000e59cca:~/bin# go get github.com/QuentinPerez/scaleway-cli
../src/src/github.com/QuentinPerez/scaleway-cli/goversion_unsupported.go:6: "Bad go version, please install a version greater than or equal to 1.5" evaluated but not used
root@733000e59cca:~/bin# eval "$(GIMME_GO_VERSION=1.2 ./gimme)"
go version go1.2 linux/amd64
root@733000e59cca:~/bin# go get github.com/QuentinPerez/scaleway-cli
../src/src/github.com/QuentinPerez/scaleway-cli/goversion_unsupported.go:6: "Bad go version, please install a version greater than or equal to 1.5" evaluated but not used
root@733000e59cca:~/bin# eval "$(GIMME_GO_VERSION=1.4 ./gimme)"
go version go1.4 linux/amd64
root@733000e59cca:~/bin# go …
```
=> Check the go version

cmd/scw/main.go, cmd/scw/main_unsupported.go
```console
root@733000e59cca:~/bin# eval "$(GIMME_GO_VERSION=1.4 ./gimme)"
go version go1.4 linux/amd64
root@733000e59cca:~/bin# go get -u github.com/QuentinPerez/scaleway-cli/cmd/scw
../src/src/github.com/QuentinPerez/scaleway-cli/cmd/scw/main_unsupported.go:6: "Bad go version, please install a version greater than or equal to 1.5" evaluated but not used
root@733000e59cca:~/bin# rm -fr /root/src/*
root@733000e59cca:~/bin# eval "$(GIMME_GO_VERSION=1.5 ./gimme)"
go version go1.5 linux/amd64
root@733000e59cca:~/bin# go get -u github.com/QuentinPerez/scaleway-cli/cmd/scw
root@733000e59cca:~/bin#
```
=> Check go version in cmd/scw too

README.md, pkg/api/api.go, pkg/cli/x_security-groups.go
=> Refactor securityGroups

README.md, pkg/api/helpers.go, pkg/commands/exec.go, pkg/commands/run.go
=> Fix #194 1/2

README.md, pkg/api/api.go, pkg/api/api_test.go, pkg/cli/main.go, pkg/cli/x_userdata.go, pkg/commands/command_test.go, pkg/commands/login.go, pkg/commands/test.go, pkg/scwversion/version.go
=> User agent

README.md, pkg/commands/exec.go
Before
```console
./scw exec toto
FATA[0000] cannot execute 'exec': Failed to get server information for 0c1e61b8-d8fc-476e-9a1c-9b218ee82604: "0c1e61b8-d8fc-476e-9a1c-9b218ee82604" not found
```
After
```console
./scw exec toto
FATA[0000] cannot execute 'exec': Failed to get server information for 0c1e61b8-d8fc-476e-9a1c-9b218ee82604: "0c1e61b8-d8fc-476e-9a1c-9b218ee82604" not found
maybe try to flush the cache with : scw _flush-cache
```
=> exec: Add warning to flush cache

examples/create-image-from-http.sh
On busybox x86_64, busybox's wget is compiled with http proxy support but without wgetrc support
This commit fills an environment file instead of writing a wgetrc file
=> Fix wget with http_proxy on busybox x86_64

Makefile, README.md, pkg/api/api.go, pkg/api/helpers.go, pkg/scwversion/version.go
- fix comment
- fix bad error message #337 
- fix commercialtype check
- use `go list`
=> little patches

README.md, pkg/api/api.go, pkg/cli/x_patch.go
```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8866a]
goroutine 1 [running]:
panic(0x4f2980, 0xc8200120c0)
/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:464 +0x3e6
github.com/scaleway/scaleway-cli/pkg/cli.runPatch(0x821a60, 0xc820084030, 0x2, 0x2, 0x0, 0x0)
/Users/quentinperez/go/src/github.com/scaleway/scaleway-cli/pkg/cli/x_patch.go:86 +0x1d7a
github.com/scaleway/scaleway-cli/pkg/cli.Start(0xc820084010, 0x4, 0x4, 0xc82011c390, 0xc82006e058, 0x0, 0x0)
/Users/quentinperez/go/src/github.com/scaleway/scaleway-cli/pkg/cli/main.go:112 +0xb88
main.main()
/Users/quentinperez/go/src/github.com/scaleway/scaleway-cli/cmd/scw/main.go:19 +0x8a
```
=> Fix nil dereference

Makefile, README.md, pkg/api/api.go, pkg/api/cache.go, pkg/cli/main.go, pkg/config/config.go
=> Clear cache between the releases

pkg/utils/utils.go
This will use HTTP_PROXY and HTTPS_PROXY environment variables in 'scw attach' command.
=> Use proxy configuration from environment in 'scw attach' command

README.md, pkg/api/api.go, pkg/api/api_test.go, pkg/api/logger.go, pkg/cli/main.go
Following #368 this PR introduces a `Logger` interface which allows us to extract the `http2curl` and `logrus` dependencies into the `cli` & `command` packages.
The `Logger` contains two functions - `LogHTTP` to handle `http.Request`, and `Log` for plain `string`.
The `cli` configures the `ScalewayAPI` instance to retain the old logging behaviour. By default, the logging is not very verbose, logging only messages & API endpoints being used.
Also, I've replaced `anonuuid` with static, fake uuids. Not sure why we need "randomized" uuids if the only concern is to sanitize logs from real credentials.
=> Introduce Logger

pkg/api/cache.go
The cache is already using `log` in different places, so replacing this single invocation with `log` instead of `logrus`.
=> Remove single logrus invocation from cache

pkg/api/api.go
While working on my [terraform provider](https://github.com/hashicorp/terraform/pull/7331) I had the need to detach IPs from servers.
This doesn't seem to be exposed in the SDK so I added a [helper function](https://github.com/hashicorp/terraform/pull/7331/commits/51d188233ade206f3b232b090f83b985cc0bcfe0). However, I think it should be public within the SDK.
One question tho: do we need to stop servers in order to detach IPs ?
=> Add DetachIP helper

pkg/api/api.go, pkg/cli/x_security-groups.go
This PR exposes the `organization_default` attribute when updating security groups.
It's possible to mark security groups as default when using the UI, however it's not possible when using the SDK. Now you can change default SGs using the SDK.
This is usefull when you want to promote a different SG to be your organizational SG.
=> Allow security groups to be marked as organizational default

pkg/api/api.go
this way you can programatically spawn a server into a specific SG
=> expose SecurityGroup on ServerDefinition

README.md, pkg/api/api.go, pkg/api/helpers.go, pkg/commands/tag.go
=> api: Add details fields in API errors

Makefile
```console
go tool vet --all=true ./cmd ./pkg
panic: inconsistent import:
func errors.New(text string) error
previously imported as:
func errors.New(text string) error
[recovered]
panic: inconsistent import:
func errors.New(text string) error
previously imported as:
func errors.New(text string) error
goroutine 1 [running]:
panic(0x2734c0, 0xc4203aebb0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc4200b81c0, 0xc4200454a0)
/usr/local/go/src/go/types/check.go:213 +0xae
panic(0x2734c0, 0xc4203aebb0)
/usr/local/go/src/runtime/panic.go:458 +0x243
go/internal/gcimporter.(*importer).declare(0xc420306f70, 0x3f4180, 0xc420437c20)
/usr/local/go/src/go/internal/gcimporter/bimport.go:175 +0x17c
go/internal/gcimporter.(*importer).obj(0xc420306f70, …
```
=> Makefile fix go vet crash

pkg/api/api.go, pkg/api/helpers.go, pkg/cli/cmd_cp.go, pkg/cli/cmd_exec.go, pkg/cli/cmd_kill.go, pkg/cli/cmd_logs.go, pkg/cli/cmd_port.go, pkg/cli/cmd_run.go, pkg/cli/cmd_top.go, pkg/commands/cp.go, pkg/commands/create.go, pkg/commands/exec.go, pkg/commands/info.go, pkg/commands/kill.go, pkg/commands/logs.go, pkg/commands/port.go, pkg/commands/run.go, pkg/commands/top.go, pkg/utils/utils.go
=> Add --user {cp,exec,kill,port,run,top}

README.md, pkg/api/api.go, pkg/api/helpers.go, pkg/commands/history.go, pkg/commands/images.go
fix unmarshal error
```console
FATA[0002] cannot execute 'images': unable to fetch volumes from the Scaleway API: json: cannot unmarshal number 5e+10 into Go value of type uint64
```
=> Fix volume size

README.md, pkg/api/api.go, pkg/api/cache.go, pkg/api/helpers.go, pkg/cli/cmd_help.go, pkg/cli/main.go, pkg/commands/attach.go, pkg/commands/images.go, pkg/commands/run.go, pkg/utils/utils.go
How to start a server at Amsterdam
```console
$ scw --region="ams1 run docker"
$ scw ps # list all server (par1/ams1) 
```
=> Prepare multi-zone

pkg/api/api.go
to quote the [Golang documentation for http.Client Do](https://godoc.org/net/http#Client.Do):
```
If the returned error is nil, the Response will contain a non-nil Body which the
user is expected to close.
```
we can simplify the current http client usage quite a lot by just moving `defer
Close()` down some lines.
before:
```
resp, err := …
if resp != nil {
defer resp.Body.Close()
}
if err != nil {
return err
}
```
after
```
resp, err := …
if err != nil {
return err
}
defer resp.Body.Close()
```
this does not change any program semantics. the change just cleans up the code a little.
=> chore/cleanup: assume response body is present

pkg/api/api.go
will fix a problem described here: https://github.com/scaleway/docker-machine-driver-scaleway/pull/64#issuecomment-292787479
=> Fix no error when getting server without ID in api

Makefile
This is a simple change to the Makefile to include linux/arm64 as a default target. I tried adding the darwin/arm64 version too, but it fails at the last step with a rather obscure error:
```
warning: unable to find runtime/cgo.a
/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: warning: ignoring file /var/folders/hy/_ppky1c912jfgvvh610qz5600000gn/T/go-link-289996183/go.o, file was built for unsupported file format ( 0xCF 0xFA 0xED 0xFE 0x0C 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /var/folders/hy/_ppky1c912jfgvvh610qz5600000gn/T/go-link-289996183/go.o
Undefined symbols for architecture x86_64:
"_main", referenced from:
implicit entry/start for main executable
ld: …
```
=> Add support for scw on Linux arm64

examples/create-image-from-http.sh
There might not be an unique stable tagged bootscript.
=> create-image-from-http.sh: do not force bootscript

pkg/api/helpers.go
This makes WaitForServerReady work for servers that only need an IPv6 address.
=> Make WaitForServerReady use IPv6 if IPv4 unavailable

pkg/api/api.go
Remove check that the current token is returned on a GET of all tokens.
=> Remove token check on login

pkg/api/api.go, pkg/cli/cmd_ps.go
This is an answer to https://github.com/scaleway/scaleway-cli/issues/446
This PR adds an example showing `scw ps` with a filter.
Should we use the --region flag passed before the command `ps` to filter the API on which the `ps` commands run upon?
=> WIP: Allow region filtering

pkg/cli/x_security-groups.go
Hello, 
There were a typo in _security-groups example.
=> Fix help typo for _security-groups

pkg/api/api.go, pkg/api/helpers.go, pkg/cli/cmd_create.go, pkg/cli/cmd_run.go, pkg/cli/x_patch.go, pkg/commands/create.go, pkg/commands/create_test.go, pkg/commands/run.go
Option allows to choose between `local`and `bootscript` boot for `scw create` and `scw run` command.
=> add boot-type option to create/run commands

README.md
Add a warning in the doc about ssh key permissions.
=> doc: warning on ssh key permissions

pkg/api/api.go, pkg/api/helpers.go, pkg/api/helpers_test.go, pkg/api/logger.go
The size of the default volume will now be resized using the following
rules:
1- the user define a custom root size
2- (default) use the largest possible size ==>
`min(categoryMaxSize,volumeMaxSize)`
3- the user specify additional volumes ==> `min(50G,volumeMaxSize)`
=> fix: create servers volumes algo

README.md
Related to: https://github.com/scaleway/homebrew-scaleway/pull/12
=> doc: remove brew tap installation instructions

pkg/api/cache.go, pkg/api/helpers.go, pkg/api/helpers_test.go, pkg/commands/create_test.go, pkg/commands/history_test.go, pkg/commands/inspect_test.go, pkg/commands/s3.go, pkg/commands/test.go
- Fix integration test (`TEST_WITH_REAL_API=1`) by updating old images:
- `ubuntu-wily` -> `ubuntu-bionic`
- `ubuntu-mini-xenial-25g/X64-2GB` -> `ubuntu-bionic/DEV1-S`
- Code is now formatted with `goimports`.
=> feat: fix integration tests

Makefile
- Drop the freebsd support for `go1.12+` due to https://github.com/moby/moby/pull/38818
=> fix: drop [free|net]bsd support for go1.12+

internal/core/autocomplete.go, internal/core/autocomplete_test.go, internal/namespaces/autocomplete/autocomplete.go
The previous implementation was using a local variable outside of a function (cf: `local can only be used in a function`).
It could be dangerous for other program autocompletions.
=> fix(autocomplete): bash arg value autocompletion

internal/core/cobra_usage_builder.go, internal/namespaces/instance/v1/instance_cli.go
```
> scw instance ip create -h
DEBUG: 2019/12/18 15:21:10 building instance.server.update: '[volumes {key} id]' has no usage and is not ignored
DEBUG: 2019/12/18 15:21:10 building instance.image.create: '[extra-volumes {key} id]' has no usage and is not ignored
Reserve an IP.
USAGE:
scw [global-flags] instance ip create [flags] [args]
ARGS:
[server]   UUID of the server you want to attach the IP to
FLAGS:
-h, --help   help for create
GLOBAL FLAGS:
--access-key string        Scaleway access key
-D, --debug                    Enable debug mode
--organization-id string   Scaleway organization ID
-o, --output PrinterType       Output format: json or human
-p, --profile string           The config profile to use
-r, --region string            The Scaleway region
--secret-key string …
```
=> fix: remove warnings for fields not ignored

internal/human/marshal.go, internal/namespaces/instance/v1/custom_marshal.go, internal/namespaces/instance/v1/updated_commands.go
* Implement `marshalInlineSlice`
* Remove `serverSummariesMarshallerFunc` as it is now the default behavior
* Add `Tags` to `humanServerInList` 🎁 
Result:
```
$ scw instance security-group list
ID                                    NAME                    [...]  SERVERS  STATEFUL
00000000-0000-1000-0000-000000000000  Default security group  [...]  3        false
22222222-2222-1222-2222-222222222222  test01                  [...]  0        true
^ a count representation as the ServerSummary is not a scalar type.
$ scw instance server get server-id=64c3ed5c-72f6-495b-94f5-f43c4536f49c
Server:
id                        00000000-0000-1000-0000-000000000000
name                      terraform-v2-doc
organization              11111111-1111-1111-1111-111111111111
allowed-actions.0         backup …
```
=> feat(core): inline marshalling for scalar slices

internal/namespaces/instance/v1/custom_marshal.go
Add servers list in the `security-group get` command.
AFAIK `serverSummariesMarshallerFunc` was not used anymore.
Result:
```
$ scw instance security-group get security-group-id=e5bf4522-94b4-4933-bebb-9b21f786b4af | anonuuid
Security Group:
id                       00000000-0000-1000-0000-000000000000
name                     Default security group
description              Auto generated security group.
enable-default-security  true
organization-id          11111111-1111-1111-1111-111111111111
use-by-default           true
creation-date            4 years ago
modification-date        1 year ago
Inbound Rules (default policy accept):
ID   PROTOCOL  ACTION  IP RANGE  DEST
Outbound Rules (default policy accept):
ID                                    PROTOCOL  ACTION  IP RANGE   DEST …
```
=> feat(instance): add servers in security-group get command

internal/namespaces/instance/v1/custom_commands.go
Fix `Data must be a marshable value (a scalar type or a Marshaler)` error.
=> fix(instance): security-group marshalling

internal/namespaces/instance/v1/custom_commands.go
Add the ability to update the organization default security group.
Worst case (copy and paste) scenariot:
```
$ scw instance security-group update security-group-id=BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB organization-default=true
Your default security group can't be stateful
Details:
You have to make this security group stateless to use it as an organization default.
More info: https://www.scaleway.com/en/docs/how-to-activate-a-stateful-cloud-firewall
Hint:
scw instance security-group update security-group-id=BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB organization-default=true stateful=false
$ scw instance security-group update security-group-id=BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB organization-default=true stateful=false
You cannot have more than one organization default
Details:
You already …
```
=> feat(instance): update organization default security group

internal/args/args.go, internal/args/errors.go, internal/args/unmarshal.go, internal/args/unmarshal_test.go, internal/e2e/testdata/test-human-list-simple.stdout.golden, internal/namespaces/instance/v1/command_server_create.go
Today it is not very explicit for a user because he can use 3 methods to fill slice:
```
slice.0=a -slice.1=b
slice=a -slice=b
slice=a,b (In custom commands like create server)
```
This PRs does:
=> fix(args): rework slices

internal/core/error.go
This hint does not make sense in many cases for example when backup are expired
=> fix: remove default hint on resource exired error

internal/core/autocomplete.go, internal/core/autocomplete_test.go, internal/core/client.go, internal/core/cobra_builder.go
=> feat(core): rm secret-key, access-key, org-id, zone global flags

internal/namespaces/autocomplete/autocomplete.go
This fix will work after fish 3.1, see https://github.com/fish-shell/fish-shell/issues/6214
=> fix(autocomplete): complete on fish subprocess

pkg/api/api.go, pkg/api/helpers.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
=> fix: change function comments based on best practices from Effective Go

cmd/scw/main.go, cmd/scw/testdata/test-all-usage-k8s-cluster-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-delete-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-get-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-list-available-versions-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-list-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-reset-admin-token-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-update-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-upgrade-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-usage.stderr.golden, cmd/scw/testdata/test-main-usage-usage.stderr.golden, internal/namespaces/k8s/v1beta4/custom.go, internal/namespaces/k8s/v1beta4/custom_cluster.go
=> feat(k8s): add k8s in available namespace

README.md
Since we download the binary with sudo, we need sudo to chmod +x it.
---
From a fellow Scaleway member 🤓
=> doc: add sudo to chmod command during install

internal/core/reflect.go, internal/core/validate.go, internal/core/validate_test.go
This PR allows to fix an issue when a required argument were in a nested structure
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
=> feat(core): implement struct required validation

internal/namespaces/k8s/v1beta4/custom_cluster.go
=> fix(k8s): return cluster on wait flags

cmd/scw/testdata/test-all-usage-k8s-pool-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-pool-delete-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-pool-update-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-pool-upgrade-usage.stderr.golden, internal/namespaces/k8s/v1beta4/custom.go, internal/namespaces/k8s/v1beta4/custom_pool.go
=> feat(k8s): add wait and status color to k8s pool

cmd/scw/testdata/test-all-usage-k8s-node-reboot-usage.stderr.golden, internal/namespaces/k8s/v1beta4/custom.go, internal/namespaces/k8s/v1beta4/custom_node.go
=> feat(k8s): add wait and status color to k8s node

cmd/scw/testdata/test-all-usage-k8s-version-get-usage.stderr.golden, cmd/scw/testdata/test-all-usage-k8s-version-usage.stderr.golden, internal/namespaces/k8s/v1beta4/custom.go, internal/namespaces/k8s/v1beta4/custom_version.go, internal/namespaces/k8s/v1beta4/custom_version_get.go, internal/namespaces/k8s/v1beta4/custom_version_get_test.go, internal/namespaces/k8s/v1beta4/testdata/test-get-version-error.cassette.yaml, internal/namespaces/k8s/v1beta4/testdata/test-get-version-error.stderr.golden, internal/namespaces/k8s/v1beta4/testdata/test-get-version-simple.cassette.yaml, internal/namespaces/k8s/v1beta4/testdata/test-get-version-simple.stdout.golden
Need the generated version commands first
=> feat(k8s): add version commands

go.mod, go.sum
=> chore(core): bump sdk version

internal/qa/qa.go
**Output**
```bash
Errors:
short must be present for command 'marketplace image'
different localization for 'k8s cluster list', 'k8s kubeconfig uninstall': [region], []
different localization for 'k8s cluster create', 'k8s kubeconfig uninstall': [region], []
different localization for 'k8s cluster get', 'k8s kubeconfig uninstall': [region], []
different localization for 'k8s cluster update', 'k8s kubeconfig uninstall': [region], []
different localization for 'k8s cluster delete', 'k8s kubeconfig uninstall': [region], []
different localization for 'k8s cluster upgrade', 'k8s kubeconfig uninstall': [region], []
different localization for 'k8s cluster list-available-versions', 'k8s kubeconfig uninstall': [region], []
different localization for 'k8s cluster reset-admin-token', 'k8s kubeconfig …
```
=> cli: check that all command are localized with QA test

internal/namespaces/k8s/v1/custom_kubeconfig_install.go
=> fix: create kubeconfig dir when it fo not exist

cmd/scw-qa/main.go, internal/qa/qa.go
Example:
```
Errors:
short must be present for command 'marketplace image'
[...]
Summary:
DuplicatedCommandError                  1
ShortMustBePresentError                 1
DifferentLocalizationForNamespaceError  22
```
=> test(qa): add a duplicated command test

cmd/scw/testdata/test-all-usage-autocomplete-install-usage.stderr.golden, cmd/scw/testdata/test-main-usage-usage.stderr.golden, internal/core/result.go, internal/namespaces/account/custom.go, internal/namespaces/account/error.go, internal/namespaces/autocomplete/autocomplete.go, internal/namespaces/init/init.go
=> feat(core): rework init command

internal/account/account.go, internal/namespaces/init/init.go
=> fix(core): better password error handling

cmd/scw/testdata/test-all-usage-instance-image-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-image-list-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-ip-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-ip-list-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-placement-group-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-placement-group-list-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-security-group-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-security-group-list-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-server-list-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-server-update-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-snapshot-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-snapshot-list-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-volume-create-usage.stderr.golden, cmd/scw/testdata/test-all-usage-instance-volume-list-usage.stderr.golden, internal/core/reflect.go, internal/namespaces/instance/v1/custom.go, internal/namespaces/instance/v1/custom_image.go, internal/namespaces/instance/v1/custom_ip.go, internal/namespaces/instance/v1/custom_placement_group.go, internal/namespaces/instance/v1/custom_security_group.go, internal/namespaces/instance/v1/custom_server.go, internal/namespaces/instance/v1/custom_snapshot.go, internal/namespaces/instance/v1/custom_volume.go
=> fix(instance): add ID suffix to organization field

internal/core/testing.go, internal/e2e/human_test.go, internal/e2e/sdk_errors_test.go, internal/namespaces/instance/v1/custom_image_test.go, internal/namespaces/instance/v1/custom_server_create_test.go, internal/namespaces/instance/v1/custom_server_test.go, internal/namespaces/instance/v1/helpers_test.go, internal/namespaces/instance/v1/instance_cli_test.go, internal/namespaces/instance/v1/ip_test.go, internal/namespaces/k8s/v1/helpers_test.go
Used to handle arguments with space in them
=> refacto(testing): Use Args as a []string

internal/args/args.go, internal/core/cobra_utils.go, internal/core/validate.go, internal/core/validate_test.go
=> fix(core): allow required nil values

internal/namespaces/baremetal/v1/custom_server.go
=> fix(baremetal): check that install status is not nil before installwait

internal/core/testing.go
=> chore(core): refactor metadata and rename Tpl to render

internal/core/testing.go, scripts/run-tests.sh
By doing so, we can avoid having developers forgetting about a given environment variable that would update cassettes when not intended to. Using explicit flags avoids those can of mistakes and can be added easily from command line run or from an IDE.
Usage example: https://blog.jbowen.dev/2019/08/using-go-flags-in-tests/
=> chore(test): move from environment to go flags to signal updating

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-server-update-usage.golden, internal/namespaces/instance/v1/custom_server.go, internal/namespaces/instance/v1/custom_server_create.go
=> feat(instance): add support for cloud-init

internal/account/account.go, internal/namespaces/init/custom_init_autocomplete_test.go, internal/namespaces/init/custom_init_ssh_test.go, internal/namespaces/init/init.go, internal/namespaces/init/init_test.go
Closes #1141 
```release-note
fix(init): rely on token organization
```
=> fix(init): rely on token organization

internal/core/error.go, internal/e2e/testdata/test-human-create-invalid-boolean.golden, internal/e2e/testdata/test-human-get-invalid-arg-name.golden, internal/e2e/testdata/test-human-get-pass-human-uuid-without-arg.golden, internal/e2e/testdata/test-sdk-standard-errors-out-of-stock.golden, internal/e2e/testdata/test-sdk-standard-errors-resource-not-found.golden, internal/e2e/testdata/test-sdk-standard-errors-transient-state.golden, internal/namespaces/baremetal/v1/testdata/test-reboot-server-errors-error-cannot-be-rebooted-while-not-delivered.golden, internal/namespaces/baremetal/v1/testdata/test-start-server-errors-error-cannot-be-started-while-not-delivered.golden, internal/namespaces/baremetal/v1/testdata/test-stop-server-errors-error-cannot-be-stopped-while-not-delivered.golden, internal/namespaces/config/testdata/test-config-delete-profile-command-unknown-profile.golden, internal/namespaces/config/testdata/test-config-get-command-unknown-profile.golden, internal/namespaces/config/testdata/test-config-unset-command-unknown-profile.golden, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-disallow-existing-root-volume-id.golden, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-instance-type.golden, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-root-volume-format.golden, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-total-local-volumes-size-too-high3.golden, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-missing-image-label.golden, internal/namespaces/instance/v1/testdata/test-create-volume-bad-size-unit.golden, internal/namespaces/instance/v1/testdata/test-server-ssh-stopped-server.golden, internal/namespaces/instance/v1/testdata/test-server-update-no-initial-placement-group&-placement-group-id=valid,-but-non-existing-pg-id.golden, internal/namespaces/instance/v1/testdata/test-server-volume-update-attach-invalid-volume-uuid.golden, internal/namespaces/instance/v1/testdata/test-server-volume-update-detach-invalid-volume-uuid.golden
=> feat(core): improve json format for CLI error

cmd/scw/testdata/test-all-usage-config-get-usage.golden, cmd/scw/testdata/test-all-usage-config-unset-usage.golden, cmd/scw/testdata/test-all-usage-instance-ip-create-usage.golden, go.mod, go.sum, internal/core/validate.go, internal/e2e/testdata/test-human-create-simple.golden, internal/e2e/testdata/test-human-create-with-args.golden, internal/e2e/testdata/test-human-delete-simple.golden, internal/e2e/testdata/test-human-get-simple.golden, internal/e2e/testdata/test-human-list-simple.golden, internal/e2e/testdata/test-human-update-multiple-args.golden, internal/e2e/testdata/test-human-update-single-arg.golden, internal/namespaces/config/testdata/test-config-dump-command-simple.golden, internal/namespaces/instance/v1/custom.go, internal/namespaces/instance/v1/custom_ip.go, internal/namespaces/instance/v1/custom_server_create.go, internal/namespaces/instance/v1/testdata/test-ip-create-simple.cassette.yaml, internal/namespaces/instance/v1/testdata/test-ip-create-simple.golden, internal/namespaces/instance/v1/testdata/test-ip-get-simple.cassette.yaml, internal/namespaces/instance/v1/testdata/test-ip-get-simple.golden, internal/namespaces/instance/v1/testdata/test-ip-list-simple.cassette.yaml, internal/namespaces/instance/v1/testdata/test-ip-list-simple.golden, internal/namespaces/instance/v1/testdata/test-ip-update-simple.cassette.yaml, internal/namespaces/instance/v1/testdata/test-ip-update-simple.golden, internal/namespaces/rdb/v1/testdata/test-clone-instance-simple.golden, internal/namespaces/rdb/v1/testdata/test-create-instance-simple.golden, internal/namespaces/rdb/v1/testdata/test-upgrade-instance-simple.golden
```release-note
feat: handle projects
```
=> feat: handle projects

internal/human/marshal.go, internal/human/marshal_func.go, internal/human/marshal_test.go, internal/namespaces/rdb/v1/custom.go, internal/namespaces/rdb/v1/custom_instance.go, internal/namespaces/rdb/v1/custom_instance_create.go, internal/namespaces/rdb/v1/custom_instance_get_test.go, internal/namespaces/rdb/v1/testdata/test-clone-instance-simple.golden, internal/namespaces/rdb/v1/testdata/test-create-instance-simple.golden, internal/namespaces/rdb/v1/testdata/test-get-instance-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-get-instance-simple.golden, internal/namespaces/rdb/v1/testdata/test-upgrade-instance-simple.golden
=> rdb: add human marshaller for instance

internal/namespaces/k8s/v1/custom.go, internal/namespaces/k8s/v1/custom_cluster.go, internal/namespaces/k8s/v1/custom_cluster_test.go, internal/namespaces/k8s/v1/helpers_test.go, internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.cassette.yaml, internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.golden
=> feat(k8s): improve human marshaller for cluster

cmd/scw/testdata/test-all-usage-k8s-cluster-wait-usage.golden, internal/namespaces/k8s/v1/custom_cluster.go, internal/namespaces/k8s/v1/custom_cluster_test.go, internal/namespaces/k8s/v1/helpers_test.go, internal/namespaces/k8s/v1/testdata/test-wait-cluster-wait-for-pools.cassette.yaml, internal/namespaces/k8s/v1/testdata/test-wait-cluster-wait-for-pools.golden
=> k8s: add option to wait for pools in the wait for cluster

README.md
=> doc: add links to CLI namespace reference documentation on README

internal/namespaces/instance/v1/custom.go, internal/namespaces/instance/v1/custom_volume_type.go, internal/namespaces/instance/v1/custom_volume_type_test.go, internal/namespaces/instance/v1/testdata/test-volume-type-list-volume-type-list.cassette.yaml, internal/namespaces/instance/v1/testdata/test-volume-type-list-volume-type-list.golden
=> feat(instance): improve human output for volume-type list

internal/human/marshal.go, internal/human/specs.go, internal/namespaces/rdb/v1/custom_instance.go, internal/namespaces/rdb/v1/custom_instance_test.go, internal/namespaces/rdb/v1/testdata/test-list-instance-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-list-instance-simple.golden
=> fix(rdb): instance list human formating

README.md
=> docs: add a section about the legacy CLI

internal/namespaces/k8s/v1/custom.go, internal/namespaces/k8s/v1/custom_cluster.go, internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.cassette.yaml, internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.golden
=> feat(k8s): add support for showing pools in get cluster

internal/qa/qa.go
=> feat(qa): add a qa about commands without examples

internal/namespaces/rdb/v1/custom.go, internal/namespaces/rdb/v1/custom_user.go, internal/namespaces/rdb/v1/custom_user_test.go, internal/namespaces/rdb/v1/testdata/test-list-user-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-list-user-simple.golden
=> feat(rdb): add privileges per databases in user list

internal/namespaces/iot/v1beta1/custom.go, internal/namespaces/iot/v1beta1/custom_device.go, internal/namespaces/iot/v1beta1/custom_hub.go
- HubStatus,
- DeviceMessageFiltersPolicy
- DeviceStatus
```release-note
```
=> feat(iot): add human marshallers for enums

docs/docker.md
Hey 👋 
I tried to use the cli inside a container following the documentation but it seems it doesn't match the v2.
I updated the documentation by adding an explicit tag (maybe too specific? But it the "v2" doesn't seem to exist). I also changed the volume since it doesn't work if you init the configuration within docker 🐳 
WDYT?
=> Update docker instructions to match v2

internal/core/printer.go, internal/core/printer_test.go, internal/core/testdata/test-yaml-printer-human-list-with-options-unknown-column.golden, internal/core/testdata/test-yaml-printer-human-list-with-options.golden, internal/core/testdata/test-yaml-printer-human-list-without-option.golden, internal/core/testdata/test-yaml-printer-human-simple-with-options.golden, internal/core/testdata/test-yaml-printer-human-simple-without-option.golden, internal/core/testdata/test-yaml-printer-nil-slice.golden
=> feat(printer): add support for YAML output

internal/core/testing.go, internal/namespaces/init/init.go, internal/namespaces/init/init_test.go, internal/namespaces/init/testdata/test-init-autocomplete-darwin-bash.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-darwin-fish.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-darwin-without.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-darwin-zsh.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-bash.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-fish.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-without.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-zsh.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-bash.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-fish.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-without.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-zsh.cassette.yaml, internal/namespaces/init/testdata/test-init-cl-iv2-config-overwrite.cassette.yaml, internal/namespaces/init/testdata/test-init-configuration-path.cassette.yaml, internal/namespaces/init/testdata/test-init-profile.cassette.yaml, internal/namespaces/init/testdata/test-init-simple.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-key-registered.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-key-unregistered.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-no-local-key.cassette.yaml
```release-note
Save the `project_id` in the config with the `scw init` command
```
=> feat(init): save project_id in config

cmd/scw/testdata/test-all-usage-rdb-backup-download-usage.golden, cmd/scw/testdata/test-all-usage-rdb-backup-usage.golden, internal/namespaces/rdb/v1/custom.go, internal/namespaces/rdb/v1/custom_backup.go, internal/namespaces/rdb/v1/custom_backup_test.go, internal/namespaces/rdb/v1/testdata/test-download-backup-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-download-backup-simple.golden
=> feat(rdb): add support for downloading a backup locally

cmd/scw/testdata/test-all-usage-k8s-kubeconfig-get-usage.golden, internal/namespaces/k8s/v1/custom_kubeconfig_get.go
=> feat(k8s): add example for kubeconfig get

cmd/scw/testdata/test-all-usage-account-ssh-key-add-usage.golden, cmd/scw/testdata/test-all-usage-baremetal-server-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-image-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-ip-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-placement-group-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-security-group-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-snapshot-create-usage.golden, cmd/scw/testdata/test-all-usage-instance-volume-create-usage.golden, cmd/scw/testdata/test-all-usage-iot-hub-create-usage.golden, cmd/scw/testdata/test-all-usage-iot-network-create-usage.golden, cmd/scw/testdata/test-all-usage-k8s-cluster-create-usage.golden, cmd/scw/testdata/test-all-usage-lbip-create-usage.golden, cmd/scw/testdata/test-all-usage-lblb-create-usage.golden, cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden, cmd/scw/testdata/test-all-usage-registry-namespace-create-usage.golden, cmd/scw/testdata/test-all-usage-vpc-private-network-create-usage.golden, internal/core/arg_specs.go, internal/core/autocomplete.go, internal/core/cobra_builder.go, internal/core/cobra_usage_builder.go, internal/core/cobra_usage_builder_test.go, internal/core/cobra_utils.go, internal/core/validate.go, internal/core/validate_test.go, internal/docgen/docgen.go, internal/docgen/tpl.go, internal/e2e/testdata/test-human-create-usage.golden, internal/namespaces/instance/v1/custom_server_create.go
This PR introduces the handling of deprecated arguments with the example of the `organization-id` field of `scw instance server create`:
- Add a `Deprecated bool` argument to `core.ArgSpec`
- Add a new `DEPRECATED ARGS` for deprecated args in the command usage.
- Ignore deprecated arguments in autocomplete
- Print a warning when a deprecated argument is …
=> feat(core): deprecate an argument

go.mod, go.sum, internal/namespaces/vpc/v1/custom.go, internal/namespaces/vpc/v1/custom_private_network.go, internal/namespaces/vpc/v1/custom_private_network_test.go, internal/namespaces/vpc/v1/helper_test.go, internal/namespaces/vpc/v1/testdata/test-get-private-network-simple.cassette.yaml, internal/namespaces/vpc/v1/testdata/test-get-private-network-simple.golden
=> feat(vpc): add support to see all servers in a given private network

cmd/scw/testdata/test-all-usage-rdb-backup-wait-usage.golden, internal/namespaces/rdb/v1/custom_backup.go
=> fix(rdb): fix argument parsing in backup wait

.github/CONTRIBUTING.md, .github/pull_request_template.md
=> doc: fix wrong image path and remove mention of the v2 branch

internal/namespaces/account/v2alpha1/custom.go, internal/namespaces/init/custom_init_ssh_test.go, internal/namespaces/init/testdata/test-init-ssh-with-local-ed25519-key.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-with-local-ed25519-key.golden
Fix the error during `scw init`:  "Except for SSH key: could not find an SSH key at ~/.ssh/id_rsa.pub" if you have a key in another format.
```release-note
NONE
```
=> feat: Adding support of ed25519 ssh key during scw init

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, internal/namespaces/instance/v1/custom_server_create.go
Closes #1365 
```release-note
add boot-type to create server
```
=> feat(instance): add boot-type to create server

internal/namespaces/k8s/v1/custom_cluster.go, internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.golden
=> fix(k8s): fix k8s get json output case

README.md, scripts/release/release.js
```release-note
fix: use dots instead of dashes in release assets name version
```
=> fix(release): use dots instead of dashes in release assets name version

cmd/scw/main.go
=> chore(main): set development version to avoid raising sentry

internal/namespaces/object/v1/s3configfile.go, internal/namespaces/object/v1/testdata/test-config-get-default-mc.golden, internal/namespaces/object/v1/testdata/test-config-get-with-region-mc.golden
Before this change, using "mc" to generate a pre-sign URL using for uploading an object would not work. After manually updating the config from S3v2 to S3v4 all good now.
Command I used is:
```bash
mc share upload scaleway/my-bucket/test.png
```
Before the change it would generate a URL like this, and it doesn't work:
```bash
$ mc share upload scaleway/my-test-bucket/test.png
URL: https://s3.fr-par.scw.cloud/my-test-bucket/test.png
Expire: 7 days 0 hours 0 minutes 0 seconds
Share: curl https://s3.fr-par.scw.cloud/my-test-bucket/ -F signature=jE27Ptr/IkDJcP60ZqA7jJD7RnE= -F bucket=my-test-bucket -F policy=eyJleHBpcmF0aW9uIjoiMxAyMC0xMS0xOVQxMTo0OTo1Mi4xMloi2CJjb25kaXRpb25zIjpbWyJlcSIsIiRidWNrZXQiLCJkYW5sb24tc3RhZ2luZy1sb2dvLXVwbG9hZHMiXSxbImVxIiwiJGtleSIsInRlc3QucG5nIl1dfQ== -F …
```
=> fix(object): mc: change generated Signature Version from v2 to v4

cmd/scw/testdata/test-all-usage-instance-server-update-usage.golden, internal/namespaces/instance/v1/instance_cli.go
before:
```
Apply the given security group to a given server
scw instance server update
Put a given server in the given placement group. Server must be off
scw instance server update
```
after:
```
Apply the given security group to a given server
scw instance server update 11111111-1111-1111-1111-111111111111 security-group-id=11111111-1111-1111-1111-111111111111
Put a given server in the given placement group. Server must be off
scw instance server update 11111111-1111-1111-1111-111111111111 placement-group=11111111-1111-1111-1111-111111111111
```
=> fix(instance): fix documentation on server update

go.mod, go.sum
=> chore: bump sdk

internal/args/args.go, internal/args/unmarshal.go, internal/core/arg_specs.go, internal/core/cobra_utils.go, internal/core/cobra_utils_test.go
```release-note
Handle maps in arguments
```
=> feat(core): handle map in request arguments

cmd/scw/testdata/test-all-usage-instance-image-create-usage.golden, internal/namespaces/instance/v1/custom_image.go
=> fix(instance): use a slice for addition snapshots in create volume

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, internal/namespaces/instance/v1/custom_server_create.go, internal/namespaces/instance/v1/custom_server_create_test.go
=> feat(instance): add ubuntu as default for image arg in server create

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, internal/core/arg_specs.go, internal/namespaces/instance/v1/custom_server_create.go
=> feat: remove deprecation warning on organization

cmd/scw/testdata/test-all-usage-apple-silicon-server-create-usage.golden, cmd/scw/testdata/test-all-usage-apple-silicon-server-delete-usage.golden, cmd/scw/testdata/test-all-usage-apple-silicon-server-reboot-usage.golden, cmd/scw/testdata/test-all-usage-apple-silicon-server-usage.golden, cmd/scw/testdata/test-all-usage-apple-silicon-server-wait-usage.golden, go.mod, go.sum, internal/namespaces/applesilicon/v1alpha1/custom.go, internal/namespaces/applesilicon/v1alpha1/custom_server.go
=> feat(as): add support for wait command and wait flag

internal/namespaces/applesilicon/v1alpha1/custom.go, internal/namespaces/applesilicon/v1alpha1/custom_server_types.go, internal/namespaces/applesilicon/v1alpha1/custom_server_types_test.go, internal/namespaces/applesilicon/v1alpha1/testdata/test-server-type-list-base.cassette.yaml, internal/namespaces/applesilicon/v1alpha1/testdata/test-server-type-list-base.golden
=> feat(as): add server type list format

internal/namespaces/account/v2alpha1/custom.go
=> typo: ssh init already present

cmd/scw/testdata/test-all-usage-k8s-cluster-create-usage.golden, internal/namespaces/k8s/v1/custom_cluster.go, internal/namespaces/k8s/v1/custom_version.go
=> feat(k8s): add a default for choosing latest version in cluster create

cmd/scw/main.go, internal/sentry/sentry.go
=> feat: add banner about scw feedback bug when a panic occurs

internal/namespaces/instance/v1/custom_server_type.go
=> fix(instance): use right zone for all calls in server-type

docs/docker.md
```release-note
- Bump docker documentation to latest current version
- Fix docker volume binding for credentials
```
=> doc: fix and update Docker documentation

README.md, cmd/scw/testdata/test-all-usage-dns-record-add-usage.golden, cmd/scw/testdata/test-all-usage-dns-record-delete-usage.golden, cmd/scw/testdata/test-all-usage-dns-record-set-usage.golden, cmd/scw/testdata/test-all-usage-dns-record-usage.golden, docs/commands/dns.md, internal/namespaces/domain/v2beta1/custom.go, internal/namespaces/domain/v2beta1/custom_record_add.go, internal/namespaces/domain/v2beta1/custom_record_delete.go, internal/namespaces/domain/v2beta1/custom_record_set.go
=> feat(dns): update set command and fix doc

cmd/scw/testdata/test-all-usage-iot-device-get-metrics-usage.golden, cmd/scw/testdata/test-all-usage-iot-hub-create-usage.golden, cmd/scw/testdata/test-all-usage-iot-hub-update-usage.golden, docs/commands/iot.md, internal/namespaces/iot/v1/iot_cli.go
=> feat(iot): add support for twins-graphite-config

cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden, docs/commands/rdb.md, internal/namespaces/rdb/v1/rdb_cli.go
=> feat(rdb): add support for PrivateNetwork and LoadBalancer in Endpoint

.github/workflows/unit-tests.yaml, go.mod, internal/core/printer.go
=> chore: bump go version

README.md
This PR is about changing the download url in the readme for what seems to be the new binaries naming convention.
```release-note
NONE
```
=> Fix readme download url

README.md
- Update Arch packaging link to [community]. Fix #2318.
- Fix Arch naming. Archlinux -> Arch Linux.
Relates OR Closes #2318
```release-note
```
=> docs: fix Arch Linux links and naming

README.md
- Current variable substitution results in invalid URL in Linux install instructions. The shell takes `$VERSION_linux_amd64` as a variable name, whereas we actually just want `$VERSION`. This wasn't a problem before as the old URL used hyphens.
Release note for [CHANGELOG](https://github.com/scaleway/scaleway-cli/blob/master/CHANGELOG …
=> docs: Fix variable substitution in Linux install URL

.goreleaser.yml, Dockerfile, scripts/build.sh
Add version arg in Dockerfile
Build with version in build script
add build arg in goreleaser
```release-note
```
=> fix: cli version in docker image

internal/namespaces/instance/v1/custom_server_create.go, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-image-label.golden, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-instance-type.golden
Pass down error to get better messages
Instead of `Bad image label 'ubuntu_focalzz' for GP1-S`
You could get
- `scaleway-sdk-go: couldn't find a matching image for the given label (ubuntu_focalzz), zone (fr-par-2) and commercial type (GP1-S)`
- `scaleway-sdk-go: denied authentication: API key does not exist`
=> fix(server_create): pass down error on bad image label

docs/migration_guide_v2.md, internal/account/account.go, internal/core/testing.go, internal/namespaces/init/testdata/test-init-autocomplete-darwin-bash.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-darwin-fish.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-darwin-without.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-darwin-zsh.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-bash.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-fish.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-without.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-zsh.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-bash.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-fish.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-without.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-windows-zsh.cassette.yaml, internal/namespaces/init/testdata/test-init-cl-iv2-config-overwrite.cassette.yaml, internal/namespaces/init/testdata/test-init-configuration-path.cassette.yaml, internal/namespaces/init/testdata/test-init-profile.cassette.yaml, internal/namespaces/init/testdata/test-init-simple.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-key-registered.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-key-unregistered.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-no-local-key.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-with-local-ed25519-key.cassette.yaml
=> feat: update Account URL and endpoints

go.mod, go.sum
Reverts scaleway/scaleway-cli#2504
=> Revert "chore(deps): bump github.com/c-bata/go-prompt from 0.2.5 to 0.2.6"

cmd/scw/main.go
Also changed default version to `v2+dev` as `v2-dev` was flagged as a release
=> feat: use debug buildinfo when no version specified

internal/namespaces/init/init.go
Access key is fetched from api, starting a prompt to get it from user before is not useful.
```go
// Get access key
apiKey, err := account.GetAPIKey(ctx, args.SecretKey)
if err != nil {
return "", &core.CliError{
Err:     err,
Details: "Failed to retrieve Access Key from the given Secret Key.",
}
}
profile := &scw.Profile{
AccessKey:             &apiKey.AccessKey,
SecretKey:             &args.SecretKey,
DefaultZone:           scw.StringPtr(args.Zone.String()),
DefaultRegion:         scw.StringPtr(args.Region.String()),
DefaultOrganizationID: &apiKey.OrganizationID,
DefaultProjectID:      &apiKey.ProjectID, // An API key is always bound to a project.
}
```
https://github.com/scaleway/scaleway-cli/blob/master/internal/namespaces/init/init.go#L278-L293
=> fix(init): remove access key prompt

.github/workflows/docs.yml, .markdownlinkcheck.json, docs/developer.md
=> chore: add automated testing for links on markdown documentation

internal/namespaces/instance/v1/custom_server.go
Currently the CLI says 'Poweroff successful for the server' where really the instance is power*ing* off, the transient state is not explicit at all.
This gets really annoying when trying to delete an Instance and the CLI replies "Instance should be powered off".
Release note for …
=> log: more accurate status Instance API

cmd/scw/testdata/test-all-usage-instance-image-update-usage.golden, cmd/scw/testdata/test-all-usage-instance-image-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom.go, internal/namespaces/instance/v1/custom_image.go, internal/namespaces/instance/v1/custom_image_test.go, internal/namespaces/instance/v1/testdata/test-image-update-add-extra-volume.cassette.yaml, internal/namespaces/instance/v1/testdata/test-image-update-add-extra-volume.golden, internal/namespaces/instance/v1/testdata/test-image-update-change-name.cassette.yaml, internal/namespaces/instance/v1/testdata/test-image-update-change-name.golden, internal/namespaces/instance/v1/testdata/test-image-update-change-public-from-default-false-to-true.cassette.yaml, internal/namespaces/instance/v1/testdata/test-image-update-change-public-from-default-false-to-true.golden
=> feat(instance): add image update command

internal/core/client.go
A regression was introduced in the 2.6.0 release where the CLI will exit with the following error:
```
scaleway-sdk-go: cannot read config file /root/.config/scw/config.yaml: no such file or directory
```
Even though all the required env vars `SCW_ACCESS_KEY`, `SCW_SECRET_KEY`, `SCW_ORGANIZATION_ID`, `SCW_DEFAULT_ORGANIZATION_ID`, `SCW_ZONE` are set.
The same invocation of the CLI used to work fine with the 2.5.x releases
Change the client creation logic to no longer require a configuration file, but instead:
* first load config from env
* if a config file is found, then load it and merge it with the env config
```release-note
fix regression where a config file was required even if all …
```
=> fix(core): do not require a config file if required env vars are set

internal/namespaces/rdb/v1/custom.go, internal/namespaces/rdb/v1/custom_backup.go, internal/namespaces/rdb/v1/testdata/test-download-backup-with-no-previous-export-backup.golden, internal/namespaces/rdb/v1/testdata/test-list-backup-simple.golden
=> fix(rdb): add missing fields on backup builder

cmd/scw/testdata/test-all-usage-container-container-deploy-usage.golden, internal/namespaces/container/v1beta1/custom.go, internal/namespaces/container/v1beta1/custom_container.go
Closes #2680 
```release-note
```
=> feat(container): add waiter to container deploy

go.mod, go.sum, internal/namespaces/lb/v1/testdata/test-add-backend-servers-with-instance-id-public-ip.golden, internal/namespaces/lb/v1/testdata/test-add-backend-servers-with-instance-id.golden, internal/namespaces/lb/v1/testdata/test-create-backend-with-instance-id-public-ip.golden, internal/namespaces/lb/v1/testdata/test-create-backend-with-instance-id.golden, internal/namespaces/lb/v1/testdata/test-create-certificate-import.golden, internal/namespaces/lb/v1/testdata/test-create-lb-simple.golden, internal/namespaces/lb/v1/testdata/test-get-backend-simple.golden, internal/namespaces/lb/v1/testdata/test-get-frontend-simple.golden, internal/namespaces/lb/v1/testdata/test-get-lb-simple.golden, internal/namespaces/lb/v1/testdata/test-list-lb-simple.golden, internal/namespaces/lb/v1/testdata/test-wait-lb-simple.golden
=> chore: bump sdk-go

internal/core/bootstrap.go, internal/core/cobra_builder.go, internal/core/command.go, internal/namespaces/get_commands.go
Base run
```
± time scw -h                
...
scw -h  0.70s user 0.05s system 172% cpu 0.434 total
```
Current
```
± time ./scw -h              
...
./scw -h  0.15s user 0.04s system 162% cpu 0.114 total
```
=> perf: optimize cli loading

cmd/scw/testdata/test-all-usage-account-usage#01.golden, cmd/scw/testdata/test-all-usage-account-usage.golden, cmd/scw/testdata/test-main-usage-usage.golden, internal/core/command.go
=> fix(core): change command signature to fix sort of same command

cmd/scw/testdata/test-main-usage-usage.golden, internal/core/bootstrap.go
default help command was generated and documented but it was shadowed by the help namespace
=> fix(core): remove default help command

README.md, cmd/scw/main.go, internal/core/autocomplete.go, internal/core/autocomplete_test.go, internal/core/autocomplete_utils.go, internal/core/bootstrap.go, internal/core/context.go
Keep it as beta for now, could crash completion
Will try to complete arguments using the list verb of the specific resource
Example:
In `instance` namespace, every `server-id` will execute `instance server list` and complete with id fields
In `marketplace image get label=`, it will fetch for `label` using list of current resource `marketplace image list`
=> feat(core/autocomplete): complete content of args using list verbs

cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden, cmd/scw/testdata/test-all-usage-rdb-instance-upgrade-usage.golden, docs/commands/rdb.md, internal/namespaces/rdb/v1/custom.go, internal/namespaces/rdb/v1/custom_instance.go, internal/namespaces/rdb/v1/testdata/test-create-instance-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-create-instance-simple.golden
=> fix(rdb): add nodetype autocompletion

cmd/scw/main.go
=> fix(main): print error before stacktrace on panic

cmd/scw/testdata/test-all-usage-dns-record-add-usage.golden, cmd/scw/testdata/test-all-usage-dns-record-set-usage.golden, docs/commands/dns.md, internal/namespaces/domain/v2beta1/custom_record_add.go, internal/namespaces/domain/v2beta1/custom_record_set.go, internal/namespaces/domain/v2beta1/domain_cli.go
Closes #2170 
In order to have a consistent behavior across all the devtools, the default TTL on all commands that add/set records is now 3600, as it already is in the terraform provider.
=> fix(dns): consistent TTL on records across the devtools

internal/core/autocomplete.go
completion for 
- `scw k8s cluster get <tab>`
- `scw instance server name=<tab>`
And a lot more arguments everywhere in the CLI
=> feat(autocomplete): remove beta check for arg completion

internal/core/shell.go
shell would crash on `scw instance server update` because of the argument `volumes.{key}` that is returned from AutoComplete as `volumes.`
=> fix(shell): crash when completing map of object

internal/core/shell.go
Shell would spam request on each character change or cursor move
Example:
- `instance server list name=|` => request
- `instance server list name=c|` => request
- `instance server list name=|c` => request
Now request get cached 
Example:
- `instance server list name=|` => request
- `instance server list name=c|`
- `instance server list name=|c`
=> feat(shell): cache last autocomplete request

internal/args/args.go, internal/core/arg_specs.go, internal/core/arg_specs_test.go, internal/core/reflect.go, internal/qa/argspec.go, internal/qa/qa.go
Closes #933 
```
ArgSpecInvalidError                     9
ArgSpecMissingError                     111
```
=> feat(qa): add argspec checking in cli qa

go.mod, go.sum, internal/tasks/loader.go, internal/tasks/tasks.go, internal/tasks/tasks_test.go
This is an helper library that allows to split a command in tasks and print the execution to the user, this also provides a way to cleanup after a failed task
Usage:
```go
ts := tasks.Begin()
ts.AddWithCleanUp("Creating container namespace", func(i interface{}) (interface{}, interface{}, error) {
time.Sleep(time.Second)
return i, "data", nil
}, func(i interface{}) error {
// i == "data"
fmt.Println("clean " + i.(string)
return nil
})
ts.Add("Creating container", func(i interface{}) (interface{}, error) {
time.Sleep(time.Second * 2)
return i, fmt.Errorf("error")
})
ts.Add("Pushing image", func(i interface{}) (interface{}, error) {
time.Sleep(time.Second * 3)
return i, nil
})
ts.Add("Deploying", func(i interface{}) (interface{}, error) {
time.Sleep(time.Second * 3)
return i, nil
})
``` …
=> feat(core): add support for composite tasks

README.md
```release-note
NONE
```
This PR adds a reference to the `function` command in the README and fixes a link where the documentation for the container command was referencing the registry API.
=> docs: add reference to function command in the README

go.mod, go.sum, internal/namespaces/config/commands.go, internal/namespaces/config/testdata/test-config-info-command-profile.golden
=> fix(config): info display overriden variables

internal/cache/cache.go, internal/core/autocomplete_utils.go, internal/core/shell.go
Previously, the quick cache feature would cache shell suggestions.
Writing
```
>>> f
function
fip
...
```
Would cache results, meaning you could not get completion when changing your word
```
>>> inst
<nothing>
```
I just added quickly a package to cache listing requests used in completion, this is very efficient when using shell.
Cache invalidate if using any other commands of this namespace, this is not perfect but it works quite well for now to avoid spamming requests and lagging out terminal.
=> feat(autocomplete): cache in arg completion instead of shell

internal/namespaces/webhosting/v1alpha1/custom.go, internal/namespaces/webhosting/v1alpha1/custom_offer.go, internal/namespaces/webhosting/v1alpha1/custom_offer_test.go, internal/namespaces/webhosting/v1alpha1/testdata/test-list-offer-simple.cassette.yaml, internal/namespaces/webhosting/v1alpha1/testdata/test-list-offer-simple.golden
=> feat(webhosting): improve offer list visualization

internal/core/shell.go
Fix #2508 
Positional args are now documented, and classic args got their doc back when using a positional argument
=> fix(shell): arg doc when using positional arguments

internal/core/build_info.go, internal/core/command.go, internal/namespaces/autocomplete/autocomplete.go
=> fix(core): add disableCheckVersion option to commands

cmd/scw/testdata/test-all-usage-config-import-usage.golden, docs/commands/config.md, internal/namespaces/config/commands.go, internal/namespaces/config/commands_test.go, internal/namespaces/config/testdata/test-config-import-command-simple.golden
=> feat(config): add import command

.github/workflows/golangci-lint.yml, .golangci.yml, cmd/scw/main.go, internal/human/marshal_func.go, internal/namespaces/account/v2alpha1/custom.go, internal/namespaces/config/commands_test.go, internal/namespaces/get_commands.go, internal/namespaces/iam/v1alpha1/custom.go, internal/namespaces/instance/v1/custom_image.go, internal/namespaces/instance/v1/custom_security_group.go, internal/namespaces/instance/v1/custom_server.go, internal/namespaces/instance/v1/custom_volume.go, internal/namespaces/lb/v1/helper_test.go, internal/namespaces/rdb/v1/custom_backup.go, internal/namespaces/rdb/v1/custom_instance.go, internal/namespaces/registry/v1/custom_docker_helper.go
=> chore: bump golang-ci lint to latest

internal/core/view.go, internal/gofields/gofields.go, internal/human/marshal.go, internal/human/marshal_test.go, internal/human/specs.go
=> feat: add an option to hide empty sections

internal/namespaces/mnq/v1alpha1/custom.go, internal/namespaces/mnq/v1alpha1/custom_credentials.go
=> feat(mnq): clean credentials display

internal/core/autocomplete.go, internal/core/autocomplete_test.go, internal/core/autocomplete_utils.go, internal/core/client.go, internal/core/context.go
=> feat(autocomplete): global flag profile values

cmd/scw/testdata/test-all-usage-instance-server-terminate-usage.golden, internal/core/cobra_builder.go, internal/core/command.go, internal/core/result.go, internal/namespaces/instance/v1/custom_server.go, internal/namespaces/instance/v1/custom_server_test.go, internal/namespaces/instance/v1/testdata/test-server-terminate-with-block.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-with-block.golden
=> feat(instance): add --wait to server terminate

internal/core/bootstrap.go, internal/core/build_info.go, internal/core/build_info_test.go, internal/core/checks.go, internal/core/checks_test.go, internal/core/cobra_utils_test.go, internal/core/command.go, internal/core/context.go, internal/core/testdata/test-check-api-key-basic.cassette.yaml, internal/core/testdata/test-check-api-key-basic.golden, internal/core/testing.go, internal/core/testing_recorder.go, internal/namespaces/autocomplete/autocomplete.go, internal/namespaces/init/testdata/test-init-ssh-key-registered.cassette.yaml
Closes #2648 
Checks example:
```
A new version of scw is available (2.14.0), beware that you are currently running 2.13.0
Current api key expires in 32m43s
```
=> feat: check for api key expiration date

internal/core/autocomplete_utils.go
Fix completion for resources containing a dash when inside another resource.
- `scw instance server update security-group-id=<tab>`
=> fix(autocomplete): complete arg of multiple word resources

cmd/scw/testdata/test-all-usage-instance-snapshot-update-usage.golden, cmd/scw/testdata/test-all-usage-instance-snapshot-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom.go, internal/namespaces/instance/v1/custom_snapshot.go, internal/namespaces/instance/v1/custom_snapshot_test.go, internal/namespaces/instance/v1/helpers_test.go, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-name.cassette.yaml, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-name.golden, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-tags.cassette.yaml, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-tags.golden
=> feat(instance): add snapshot update

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom_server_create.go, internal/namespaces/instance/v1/custom_server_create_test.go, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-additional-volume-snapshot-id.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-additional-volume-snapshot-id.golden, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-root-volume-snapshot-id.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-root-volume-snapshot-id.golden, internal/namespaces/instance/v1/testdata/test-create-server-volumes-valid-double-snapshot.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-volumes-valid-single-local-snapshot.cassette.yaml
Closes #1905 
Can be used as
`scw instance server create root-volume=local:<snapshot_id> additional-volumes.0=block:<snapshot_id>`
=> feat(instance): server create using snapshots

internal/core/validate.go, internal/namespaces/init/init.go, internal/namespaces/init/prompt.go, internal/namespaces/init/testdata/test-init-autocomplete-linux-bash.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-fish.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-without.cassette.yaml, internal/namespaces/init/testdata/test-init-autocomplete-linux-zsh.cassette.yaml, internal/namespaces/init/testdata/test-init-cl-iv2-config-no-overwrite.cassette.yaml, internal/namespaces/init/testdata/test-init-configuration-path.cassette.yaml, internal/namespaces/init/testdata/test-init-profile.cassette.yaml, internal/namespaces/init/testdata/test-init-simple.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-key-registered.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-key-unregistered.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-key-unregistered.golden, internal/namespaces/init/testdata/test-init-ssh-no-local-key.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-with-local-ed25519-key.cassette.yaml, internal/namespaces/init/testdata/test-init-ssh-with-local-ed25519-key.golden
Prepare for #2792 
Only thing that has changed currently is the order and the override message, we still ask for the same inputs.
```
Enter a valid secret-key: <secret-key>
Enter a valid access-key: <access-key>
Choose your default organization ID: <orgID>
Default project ID: <projID>
To improve this tool we rely on diagnostic and usage data.
Sending such data is optional and can be disabled at any time by running "scw config set send-telemetry=false".
Do you want to send usage statistics and diagnostics? (Y/n): n
To fully enjoy Scaleway CLI we recommend you install autocomplete support in your shell.
Do you want to install autocomplete? (Y/n): n
Creating new config
Config saved at /home/julescasteran/.config/scw/config.yaml:
access_key: <access-key>
secret_key: <secret-key> …
```
=> refactor: init command

.github/workflows/unit-tests.yaml, .goreleaser.yml, scripts/build.sh, scripts/check-size.sh
=> ci: strip binaries and check size

internal/namespaces/init/init.go, internal/namespaces/init/init_test.go, internal/namespaces/init/prompt.go, internal/namespaces/init/testdata/test-init-cl-iv2-config-no-prompt-overwrite-for-new-profile.cassette.yaml, internal/namespaces/init/testdata/test-init-cl-iv2-config-no-prompt-overwrite-for-new-profile.golden, internal/namespaces/init/testdata/test-init-cl-iv2-config-prompt-overwrite-for-existing-profile.cassette.yaml, internal/namespaces/init/testdata/test-init-cl-iv2-config-prompt-overwrite-for-existing-profile.golden
Improvement for init rework #2792 
Lookup https://github.com/scaleway/scaleway-cli/issues/2792#issuecomment-1520057224
Now we get an override prompt only when doing init for an existing profile. There is not prompt for `scw init -p mynewprofile`
Also the override prompt has changed, it only print the profile that will be override instead of the whole config
=> feat(init): no overwrite prompt when adding a new profile

cmd/scw/testdata/test-all-usage-container-container-create-usage.golden, cmd/scw/testdata/test-all-usage-container-container-update-usage.golden, cmd/scw/testdata/test-all-usage-container-namespace-update-usage.golden, internal/namespaces/container/v1beta1/custom.go, internal/namespaces/container/v1beta1/custom_container.go, internal/namespaces/container/v1beta1/custom_namespace.go
=> feat(container): add waiters

internal/namespaces/rdb/v1/custom_user.go
Listing users with a name filter would crash as listed permissions are for all users
=> fix(rdb): listing user crash with filter

cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden, cmd/scw/testdata/test-all-usage-rdb-user-create-usage.golden, cmd/scw/testdata/test-all-usage-rdb-user-update-usage.golden, docs/commands/rdb.md, internal/namespaces/rdb/v1/custom.go, internal/namespaces/rdb/v1/custom_instance.go, internal/namespaces/rdb/v1/custom_instance_test.go, internal/namespaces/rdb/v1/custom_user.go, internal/namespaces/rdb/v1/custom_user_test.go, internal/namespaces/rdb/v1/testdata/test-create-instance-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-create-instance-simple.golden, internal/namespaces/rdb/v1/testdata/test-create-instance-with-password-generator.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-create-instance-with-password-generator.golden, internal/namespaces/rdb/v1/testdata/test-create-user-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-create-user-simple.golden, internal/namespaces/rdb/v1/testdata/test-create-user-with-password-generator.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-create-user-with-password-generator.golden, internal/namespaces/rdb/v1/testdata/test-update-user-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-update-user-simple.golden, internal/namespaces/rdb/v1/testdata/test-update-user-with-password-generator.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-update-user-with-password-generator.golden, internal/passwordgenerator/password_generator.go, internal/passwordgenerator/password_generator_test.go
=> feat(rdb): add password generator

cmd/scw-wasm/async.go, cmd/scw-wasm/main.go, cmd/scw-wasm/run.go, internal/jshelpers/function.go, internal/jshelpers/objects.go, internal/wasm/run.go, wasm/cli.d.ts, wasm/index.d.ts, wasm/package.json, wasm/src/cli.test.ts
=> feat(wasm): return custom object

cmd/scw/testdata/test-all-usage-k8s-cluster-migrate-to-private-network-usage.golden, docs/commands/k8s.md, internal/namespaces/k8s/v1/custom.go, internal/namespaces/k8s/v1/custom_migrate.go
This PR adds the temporary command `scw k8s cluster migrate-to-private-network` to the CLI.
It will be used to migrate legacy clusters (those created without a private network) to clusters with a private network.
=> feat(k8s): add cluster migrate-to-private-network command

.github/workflows/wasm.yml, cmd/scw-wasm-tester/args.go, cmd/scw-wasm-tester/main.go, cmd/scw-wasm-tester/slices.go, internal/core/wasm.go, internal/jshelpers/arrays.go, internal/jshelpers/async.go, internal/jshelpers/errors.go, internal/jshelpers/function.go, internal/jshelpers/objects.go, internal/jshelpers/types.go, internal/wasm/autocomplete.go, scripts/run-tests-wasm.sh, wasm/.gitignore, wasm/cli.d.ts, wasm/index.d.ts, wasm/package.json, wasm/src/cli.test.ts, wasm/src/jshelpers.test.ts, wasm/src/utils.ts, wasm/wasm_exec.d.ts
Closes #3111 
Closes #3114 
Currently not using directly autocomplete as it requires a filled Context, will be done in the future.
The completion tree is built upon each call.
=> feat(wasm): export an autocomplete function

internal/gofields/gofields.go
Human marshal of slice fields would crash if requesting a wrong index.
Example: `scw instance server list -ohuman=Tags.0` with no tags on server
=> fix: slice field marshaling out of bound

go.mod, go.sum, internal/args/unmarshal.go
Time parsing would crash with an empty string
To reproduce: `scw rdb backup create expires-at=""`
Bump tparse dependency to fix other crash: `scw rdb backup create expires-at="0"`
=> fix(args): empty time parsing

internal/core/shell.go
Fixed crash when doing
```
$ scw shell
>>> instance -h
```
It also produced an invalid behavior when using a help flag after running a valid command
=> fix(shell): crash on help flag

cmd/scw/main.go, go.mod, go.sum, internal/core/build_info.go, internal/core/cobra_utils.go, internal/core/shell.go, internal/sentry/sentry.go
Switch to the new sentry sdk. The stack trace is cleaned up.
Added some informations to the report:
- The command used
- The list of arguments used without their content
- The CLI version as release
=> feat: improve sentry reports

cmd/scw/testdata/test-all-usage-config-dump-usage.golden, cmd/scw/testdata/test-all-usage-config-get-usage.golden, cmd/scw/testdata/test-all-usage-config-info-usage.golden, cmd/scw/testdata/test-all-usage-config-set-usage.golden, internal/namespaces/config/commands.go, internal/namespaces/init/init.go, internal/qa/qa.go, internal/qa/seealso.go
Fix #3194 
Fix seealso commands, remove extra `--help`.
Also add a qa rule to validate commands, there is still some to fix. Has to be done on generation side, I made an MR.
=> docs: update invalid seealso commands

internal/namespaces/init/init.go, internal/namespaces/init/prompt.go
use simple prompt if apiKey cannot list projects
use default project ID if not in an interactive environment
It would crash if the api key is an application key without AccountRead permission.
Fix #3193
=> fix(init): project ID prompt

cmd/scw-wasm/main.go, internal/human/marshal.go, internal/interactive/utils.go, internal/jshelpers/objects.go, internal/jshelpers/scalar.go, internal/terminal/terminal_wasm.go, internal/wasm/autocomplete.go, internal/wasm/output.go, internal/wasm/run.go, wasm/cli.d.ts, wasm/package.json, wasm/src/cli.test.ts
=> feat(wasm): add configuration to terminal size

internal/namespaces/instance/v1/custom_ssh_config.go
`scw instance ssh install-config` would crash if an instance doesn't have a public ip
=> fix(instance): ssh install-config server without public ip

internal/namespaces/instance/v1/custom_image.go, internal/namespaces/instance/v1/testdata/test-image-list-simple.golden
=> fix(instance): complete image list fields

cmd/scw/testdata/test-all-usage-instance-ssh-install-config-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom_ssh_config.go
Fix #3270 
Did a quickfix to check invalid zone per product. Should get fixed with custom sdk error
=> fix(instance): ssh-config-install invalid zone or all

README.md, scripts/get.sh
Should work on Linux, macOS and FreeBSD.
To test this PR:
```sh
curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/feat/get-script/scripts/get.sh | sh
```
Can also be done inside a container:
```sh
docker run -it --rm ubuntu bash -c "\
apt-get update \
&& apt install -y curl \
&& curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/feat/get-script/scripts/get.sh | sh \
&& scw --help"
```
=> feat: add get.sh script

docs/docker.md
When executing the `scw` command using Podman with SELinux in enforcing mode, a permission denial may be encountered when attempting to access the `config.yaml` file on the host. This commit provides a small update to the documentation to remedy this issue and run a rootless container seamlessly while maintaining SELinux in enforcing mode.
=> Added instruction to run the Docker image with Podman

internal/namespaces/rdb/v1/custom_user.go
The `rdb user list` do a second requests to get privileges but it did not use the region passed as argument `region=nl-ams`
=> fix(rdb): user list region

internal/namespaces/k8s/v1/custom_cluster.go
=> fix(k8s): fix empty PNID when not created alongside cluster

internal/namespaces/instance/v1/custom_server.go, internal/namespaces/instance/v1/custom_server_create_test.go, internal/namespaces/instance/v1/testdata/test-create-server-scratch-storage-default-scratch-storage.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-scratch-storage-default-scratch-storage.golden
=> fix(instance): server delete with scratch storage

cmd/scw-wasm-tester/human.go, cmd/scw-wasm-tester/main.go, cmd/scw-wasm/main.go, cmd/scw-wasm/run.go, internal/wasm/autocomplete.go, internal/wasm/run.go, wasm/package.json, wasm/pnpm-lock.yaml, wasm/src/cli.test.ts, wasm/src/jshelpers.test.ts, wasm/src/utils.ts
=> fix(wasm): version command

cmd/scw/testdata/test-all-usage-instance-image-create-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom_image.go
=> fix(instance): image create additional volumes field

internal/namespaces/rdb/v1/custom_backup.go, internal/namespaces/rdb/v1/testdata/test-create-backup-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-create-backup-simple.golden, internal/namespaces/rdb/v1/testdata/test-download-backup-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-download-backup-with-no-previous-export-backup.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-export-backup-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-export-backup-simple.golden, internal/namespaces/rdb/v1/testdata/test-list-backup-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-list-backup-simple.golden, internal/namespaces/rdb/v1/testdata/test-restore-backup-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-restore-backup-simple.golden
Closes #1434 
The feature was already implemented by @yfodil, this PR just adds a message to inform the user that the backup is being exported.
=> feat(rdb): print messages while exporting backup

README.md
The old URL returns 404 now.
```release-note
NONE
```
=> chore: Update Arch Linux package URL in README.md

internal/args/unmarshal.go
scw.Duration was handled as two scalar fields
This would require a change of generator to have the durations as a flat field. Draft is available for it with # 321.
=> feat(args): handle scw.Duration unmarshal as flat field

internal/gotty/client.go
=> chore(gotty): add error wrapping

cmd/scw/testdata/test-all-usage-jobs-definition-start-usage.golden, cmd/scw/testdata/test-all-usage-jobs-run-wait-usage.cassette.yaml, cmd/scw/testdata/test-all-usage-jobs-run-wait-usage.golden, docs/commands/jobs.md, internal/namespaces/jobs/v1alpha1/custom.go, internal/namespaces/jobs/v1alpha1/custom_job_definition.go, internal/namespaces/jobs/v1alpha1/custom_job_run.go
=> feat(jobs): add waiters

internal/namespaces/redis/v1/custom.go, internal/namespaces/redis/v1/custom_cluster.go
=> fix(redis):better vizualization acl redis

internal/namespaces/rdb/v1/custom_instance.go
=> feat(instance): auto completion in rdb instance command

.golangci.yml, internal/core/cobra_usage_builder.go, internal/core/command.go, internal/interactive/print.go, internal/namespaces/instance/v1/custom_server.go, internal/namespaces/object/v1/s3configfile.go, internal/namespaces/registry/v1/custom_docker_helper.go, internal/namespaces/registry/v1/helpers_login_logout.go, internal/passwordgenerator/password_generator.go
=> chore: add new linters

internal/namespaces/vpc/v2/custom_private_network.go
CMD ISSUE :
- vpc private-network get
ISSUE :
when vpc with no redis cluster attach to issue because of nil pointer
=> fix(vpc): check that redis endpoint is not nil 

scripts/get.sh
If you try to run a docker build with `--platform=linux/amd64,linux/arm64`, you'll get an error:`aarch64 is not supported by this installation script`
```release-note
feat: add aarch64 installation support with get script
```
=> feat: support aarch64 in get script

.gitignore, cmd/scw/testdata/test-all-usage-mnq-nats-create-context-usage.golden, cmd/scw/testdata/test-all-usage-mnq-nats-usage.golden, docs/commands/autocomplete.md, docs/commands/mnq.md, internal/namespaces/mnq/v1beta1/custom.go, internal/namespaces/mnq/v1beta1/custom_nats.go, internal/namespaces/mnq/v1beta1/custom_nats_helpers.go, internal/namespaces/mnq/v1beta1/custom_nats_prompt.go, internal/namespaces/mnq/v1beta1/custom_nats_test.go, internal/namespaces/mnq/v1beta1/helpers_test.go, internal/namespaces/mnq/v1beta1/testdata/test-create-context-no-interactive-term-and-multi-account-multi-nats-account-and-no-id.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-no-interactive-term-and-multi-account-multi-nats-account-and-no-id.golden, internal/namespaces/mnq/v1beta1/testdata/test-create-context-no-interactive-term-and-multi-account-simple.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-no-interactive-term-and-multi-account-simple.golden, internal/namespaces/mnq/v1beta1/testdata/test-create-context-simple.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-simple.golden, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-interative-term-and-multi-account-multi-nats-account-and-no-id.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-interative-term-and-multi-account-multi-nats-account-and-no-id.golden, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-no-account-simple.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-no-account-simple.golden, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-no-account-with-no-nats-account.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-no-account-with-no-nats-account.golden, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-wrond-id-simple.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-wrond-id-simple.golden, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-wrong-id-wrong-account-id.cassette.yaml, internal/namespaces/mnq/v1beta1/testdata/test-create-context-with-wrong-id-wrong-account-id.golden
=> feat(mnq): add a create-context nats custom command

internal/namespaces/instance/v1/custom_server_create.go
Routed IPs are getting enabled per default.
This fix: `scw instance server create` with an API that enable `routed_ip_enabled` per default.
Before this fix, the server is created with `routed_ip_enabled=true` but the IP will be created as NAT because the CLI do that when `routed-ip-enabled` is omitted.
=> fix(instance): use routed-ip-enabled for IP type when explicit

go.mod, go.sum, internal/namespaces/block/v1alpha1/custom.go
=> chore: bump scaleway sdk-go

cmd/scw/testdata/test-all-usage-instance-server-delete-usage.golden, internal/namespaces/instance/v1/custom_server.go, internal/namespaces/vpc/v2/custom.go, internal/namespaces/vpc/v2/custom_private_network.go, internal/namespaces/vpc/v2/helper_test.go, internal/namespaces/vpc/v2/testdata/test-get-private-network-multiple.cassette.yaml, internal/namespaces/vpc/v2/testdata/test-get-private-network-multiple.golden, internal/namespaces/vpc/v2/testdata/test-get-private-network-simple.cassette.yaml, internal/namespaces/vpc/v2/testdata/test-get-private-network-simple.golden
```release-note
```
close #3322
=> fix(vpc):better rendering of subnet in private network

.github/workflows/release.yml
Scaleway's cli is listed in homebrew-core [autobump list](https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt).
This now blocks the CI from making a manual bump PR using homebrew formulae bump tool.
CI output:
```
Error: Whoops, the scw formula has its version update
pull requests automatically opened by BrewTestBot!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt
```
=> ci(release): remove homebrew bump

internal/namespaces/secret/v1beta1/custom.go
Add a new option 'field' to the secret version access subcommand. This option allows to retrieve only the JSON field with the given name from a Secret Version. The Secret Version data must be in JSON format.
Add a new option 'raw' to the secret version access subcommand. This option allows to retrieve only the raw payload of a Secret Version. This option was added because the change in https://github.com/scaleway/scaleway-cli/pull/3721 is a breaking change.
```release-note
* **sem**: add option 'raw' to secret version access to retrieve the raw payload only
* **sem**: add option 'field' to secret version access to retrieve a JSON field
```
=> feat(secret-manager): add option 'field' and 'raw' to secret version accesss

cmd/scw/testdata/test-all-usage-rdb-acl-set-usage.golden, docs/commands/rdb.md, internal/core/cobra_utils.go, internal/namespaces/rdb/v1/custom_acl.go, internal/namespaces/rdb/v1/custom_acl_test.go, internal/namespaces/rdb/v1/testdata/test-set-acl-multiple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-set-acl-multiple.golden, internal/namespaces/rdb/v1/testdata/test-set-acl-simple.cassette.yaml, internal/namespaces/rdb/v1/testdata/test-set-acl-simple.golden
Closes #3596 
UI breaking change
Needs #3722 first
TODO:
--> belongs in a separate PR
=> feat(rdb): acl set simplified [UI breaking-change]

internal/namespaces/instance/v1/custom_server_type.go
Fix #3752 
Default to unknown availability if API response miss a server-type. API seems to be a bit random using this route.
=> fix(instance): show unknown server-type availability when missing

internal/namespaces/container/v1beta1/custom_deploy.go, internal/namespaces/container/v1beta1/custom_deploy_disabled.go, internal/namespaces/container/v1beta1/custom_deploy_helpers.go
"deploy" commands needs `github.com/buildpacks/lifecycle` and `github.com/buildpacks/lifecycle/path` is currently supported only by `darwin`, `linux` and `windows`.
Adjust the logic to only consider those 3 platforms instead of excluding only `wasm` and `freebsd`.
---
Noticed while building `scw` on NetBSD (but should affects all platforms that are not WASM, FreeBSD, macOS and Linux (e.g. other BSDs, Solaris)).
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull …
=> fix(container): limit to platforms supported by github.com/buildpacks/lifecycle

cmd/scw/testdata/test-all-usage-autocomplete-install-usage.golden, docs/commands/autocomplete.md, internal/namespaces/autocomplete/autocomplete.go, internal/namespaces/init/init.go
=> fix(autocomplete): add basename arg for custom path

cmd/scw/testdata/test-all-usage-dedibox-billing-list-invoice-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-billing-list-refund-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-fip-get-quota-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-fip-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-ipv6-block-create-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-ipv6-block-get-quota-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-ipv6-block-get-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-offer-get-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-offer-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-os-get-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-os-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-info-get-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-info-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-v1-list-capable-san-server-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-v1-list-capable-server-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-v1-list-members-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-v1-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-v2-list-capable-resources-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-rpn-v2-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-san-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-server-list-usage.golden, cmd/scw/testdata/test-all-usage-dedibox-service-list-usage.golden, docs/commands/autocomplete.md, docs/commands/dedibox.md, internal/core/context.go, internal/namespaces/dedibox/v1/custom.go
=> fix(dedibox): set default value project-id

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom_server_create.go, internal/namespaces/instance/v1/custom_server_create_builder.go, internal/namespaces/instance/v1/custom_server_create_test.go
=> refactor(instance): extract functions from server create command

internal/namespaces/dedibox/v1/custom.go
=> fix(dedibox): remove command from custom setProjectDefaultValue

internal/namespaces/instance/v1/custom_server_create_test.go, internal/namespaces/instance/v1/testdata/test-create-server-volumes-valid-single-local-snapshot-without-image.cassette.yaml
=> test(instance): server create with snapshot and no image 

cmd/scw/testdata/test-all-usage-vpc-usage.golden, cmd/scw/testdata/test-all-usage-vpc-vpc-usage.golden, docs/commands/vpc.md, internal/core/command.go, internal/namespaces/vpc/v2/custom.go, internal/namespaces/vpc/v2/vpc_cli.go
Should have been made by scaleway-bot. Extracted from #3983
=> feat(vpc): add route resource

internal/namespaces/cockpit/v1/cockpit_cli.go
Should have been made by scaleway-bot. Extracted from #3983
=> feat(cockpit/v1): add datasource update command

internal/core/error.go, internal/namespaces/baremetal/v1/helpers_test.go, internal/namespaces/iam/v1alpha1/error.go, internal/namespaces/instance/v1/custom_server_create.go, internal/namespaces/rdb/v1/custom_instance.go
=> fix linter error

.golangci.yml, internal/args/marshal_test.go, internal/args/unmarshal_test.go, internal/core/cobra_utils_test.go, internal/core/result_test.go, internal/core/testing.go, internal/namespaces/instance/v1/instance_cli_test.go
=> chore: add support for testifylint

.golangci.yml
=> chore: add support for gomoddirectives

cmd/scw/main.go, core/build_info.go, core/testing.go, internal/namespaces/feedback/custom_test.go, internal/namespaces/feedback/testdata/test-feedback-bug-simple.golden, internal/namespaces/feedback/testdata/test-feedback-feature-simple.golden, internal/namespaces/info/testdata/test-info-show-secret.golden, internal/namespaces/info/testdata/test-info-simple.golden
=> chore: migrate the user-agent definition to the main package

internal/namespaces/autocomplete/autocomplete.go, internal/namespaces/init/init_test.go
=> test(init): override SHELL variable to not depend on local shell

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom_server_create.go
=> fix(instance): undocument routed-ip-enabled

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom_server_create.go
Instance API already handle it as true per default
```release-note
```
=> docs(instance): add dynamic-ip-required default value

cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden, docs/commands/instance.md, internal/namespaces/instance/v1/custom_image_test.go, internal/namespaces/instance/v1/custom_ip_test.go, internal/namespaces/instance/v1/custom_placement_group_test.go, internal/namespaces/instance/v1/custom_server_action_test.go, internal/namespaces/instance/v1/custom_server_create.go, internal/namespaces/instance/v1/custom_server_create_test.go, internal/namespaces/instance/v1/custom_server_test.go, internal/namespaces/instance/v1/custom_user_data_test.go, internal/namespaces/instance/v1/helpers_test.go, internal/namespaces/instance/v1/instance_cli_test.go, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-total-local-volumes-size-too-low2.cassette.yaml, internal/namespaces/lb/v1/helper_test.go, internal/namespaces/vpc/v2/helper_test.go
DEV1-S is not available in certain AZ, we remove the default type instead of changing every time Scaleway change its hardware
=> fix(instance): remove hardcoded offers

.github/workflows/nightly.yml
=> ci: add support for nightly tests

.github/workflows/nightly.yml
=> ci: fix test invocation command

internal/namespaces/init/prompt.go
Fix https://github.com/scaleway/scaleway-cli/issues/4299
=> fix: add better error handling for init

scripts/windows/install.ps1
=> feat: add support for a powershell install script for a dev env

core/testing.go, internal/namespaces/instance/v1/custom_image_test.go, internal/namespaces/instance/v1/custom_server_action_test.go, internal/namespaces/instance/v1/custom_server_create_test.go, internal/namespaces/instance/v1/custom_server_rdp_test.go, internal/namespaces/instance/v1/custom_server_test.go, internal/namespaces/instance/v1/testdata/test-server-terminate-without-ip.cassette.yaml, internal/testhelpers/helpers.go
I added helpers to core/testing in a previous PR to help use write tests. I moved these helpers to testhelpers to avoid adding more to core.
I also used these new helpers in some instance tests.
The goal of those helpers is to limit test crashing. If a test crash, it will stop the whole test suite. If we make tests fail on failed type assertions, the rest of the test suite will still run.
=> test: move type assertion helpers to testhelpers package

internal/namespaces/iam/v1alpha1/custom_rule_test.go, internal/namespaces/iam/v1alpha1/custom_test.go
Prevent failing tests to crash in nightly tests.
=> test(iam): prevent type assertion from crashing

core/arg_file_content.go
When the command allow for a file to be loaded, the argument as io.Reader would be read, thus preventing the argument from being used in the command afterward.
Issue can be reproduced with `scw instance user-data set server-id={server_id} key=foo content="bar"`.
The `bar` string would be read to search for a `@`, then it would not be available once the command really runs.
=> fix(core): recreate io.Reader after read during file loading

internal/namespaces/k8s/v1/custom_execcredentials_test.go
These tests create their own profiles to test how env is loaded. We must ignore env variables that are used to run the tests as they collide with test's profiles
=> test(k8s): ignore scw env variable in exec-credentials tests

cmd/scw-sweeper/main.go
=> ci: add warning when configuration file is not present

cmd/scw/testdata/test-all-usage-block-volume-usage.golden, cmd/scw/testdata/test-all-usage-block-volume-wait-usage.golden, docs/commands/block.md, internal/namespaces/block/v1alpha1/custom.go, internal/namespaces/block/v1alpha1/custom_volume.go
It would be great to be able to wait for a volume to be detached. Some of our instance's tests currently use `instance volume wait` but will need this new command when we switch to sbs volumes.
=> feat(block): add volume wait command

cmd/scw/testdata/test-all-usage-block-snapshot-create-usage.golden, cmd/scw/testdata/test-all-usage-block-snapshot-usage.golden, cmd/scw/testdata/test-all-usage-block-snapshot-wait-usage.golden, cmd/scw/testdata/test-all-usage-block-volume-create-usage.golden, docs/commands/block.md, internal/namespaces/block/v1alpha1/custom.go, internal/namespaces/block/v1alpha1/custom_snapshot.go, internal/namespaces/block/v1alpha1/custom_snapshot_test.go, internal/namespaces/block/v1alpha1/custom_volume.go, internal/namespaces/block/v1alpha1/custom_volume_test.go, internal/namespaces/block/v1alpha1/helpers_test.go, internal/namespaces/block/v1alpha1/testdata/test-snapshot-wait-wait-command.cassette.yaml, internal/namespaces/block/v1alpha1/testdata/test-snapshot-wait-wait-command.golden, internal/namespaces/block/v1alpha1/testdata/test-snapshot-wait-wait-flag.cassette.yaml, internal/namespaces/block/v1alpha1/testdata/test-snapshot-wait-wait-flag.golden, internal/namespaces/block/v1alpha1/testdata/test-volume-wait-wait-command.cassette.yaml, internal/namespaces/block/v1alpha1/testdata/test-volume-wait-wait-command.golden, internal/namespaces/block/v1alpha1/testdata/test-volume-wait-wait-flag.cassette.yaml, internal/namespaces/block/v1alpha1/testdata/test-volume-wait-wait-flag.golden
Adding more waiters to use in #4435
=> feat(block): add snapshot wait command 

internal/namespaces/instance/v1/custom_server_action_test.go, internal/namespaces/instance/v1/custom_server_create_builder.go, internal/namespaces/instance/v1/custom_server_create_test.go, internal/namespaces/instance/v1/custom_server_test.go, internal/namespaces/instance/v1/helpers_test.go, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-additional-volume-snapshot-id.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-root-volume-snapshot-id.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-total-local-volumes-size-too-low2.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-volumes-valid-additional-block-volumes.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-server-volumes-valid-double-snapshot.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-delete-only-block-volumes.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-delete-only-block-volumes.golden, internal/namespaces/instance/v1/testdata/test-server-delete-only-local-volumes.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-delete-with-all-volumes.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-delete-with-all-volumes.golden, internal/namespaces/instance/v1/testdata/test-server-delete-with-none-volumes.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-with-block.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-with-block.golden, internal/namespaces/instance/v1/testdata/test-server-terminate-without-block.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-without-block.golden, internal/namespaces/instance/v1/testdata/test-server-update-custom-volumes-detach-all-volumes.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-volume-update-detach-simple-block-volume.cassette.yaml
`b` and `block` volume options are now the same as `sbs`. Instance `b_ssd` is no longer supported.
=> feat(instance): use sbs api for block volumes 

.github/workflows/deploy-docs.yml
=> fix(docs): update AWSCLI install procedure in workflow

go.mod, go.sum
Bump sdk-go with an important fix: https://github.com/scaleway/scaleway-sdk-go/pull/2406
=> chore: bump scw sdk-go

README.md, docs/commands/index.md, docs/mkdocs.yml
Fixed typo, removed warning on non-latest version, updated readme
```release-note
NONE
```
=> docs(general): update Readme and doc conf file

internal/namespaces/inference/v1beta1/custom_endpoint.go, internal/namespaces/inference/v1beta1/helper_test.go
=> fix(inference): attach private network

internal/namespaces/audit_trail/v1alpha1/custom.go, internal/namespaces/audit_trail/v1alpha1/custom_event.go
=> feat(audit-trail): improve visualization for event list

core/client.go, internal/platform/terminal/terminal_client.go
=> feat(instance): redirect to scw login when no credentials are provided

core/arg_specs.go, core/cobra_utils.go, core/cobra_utils_test.go
```release-note
- Support different arguments with positional=true
- When multiple positional args are used, the last one of the ArgSpecs is actually positional, others are dymanic
- If a positional arg is passed dymanically `arg=value`, …
```
=> feat(core): support positional args as dynamic args as well

.github/workflows/deploy-docs.yml
New integrity headers on PUT & POST requests break Actions workflow, workaround is to downgrade to a functional release (tested with this specific use case).
[Related Scaleway status](https://status.scaleway.com/incidents/pfxfkq48n8q6)
```release-note
NONE
```
=> fix(docs): downgrade awscli version for docs workflow

internal/namespaces/instance/v1/custom_server.go, internal/namespaces/instance/v1/testdata/test-get-server-simple.cassette.yaml, internal/namespaces/instance/v1/testdata/test-get-server-simple.golden
=> feat(instance): render block volumes details when getting a server

internal/namespaces/instance/v1/custom.go, internal/namespaces/instance/v1/custom_server_type.go
=> feat(instance): display server details for get-compatible-types

internal/namespaces/instance/v1/custom_image.go, internal/namespaces/instance/v1/custom_image_test.go, internal/namespaces/instance/v1/testdata/test-image-list-with-sbs-additional-volumes.cassette.yaml, internal/namespaces/instance/v1/testdata/test-image-list-with-sbs-additional-volumes.golden, internal/namespaces/instance/v1/testdata/test-image-list-with-sbs-root-volume.cassette.yaml, internal/namespaces/instance/v1/testdata/test-image-list-with-sbs-root-volume.golden
The command `scw instance image list` now fetches volume information from the SBS API to display the correct size of the underlying snapshots.
=> fix(instance): display sbs volumes' size in `instance image list` details

internal/namespaces/instance/v1/custom_server_action.go, internal/namespaces/instance/v1/custom_server_action_test.go, internal/namespaces/instance/v1/testdata/test-server-terminate-with-block.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-with-block.golden, internal/namespaces/instance/v1/testdata/test-server-terminate-with-ip.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-with-ip.golden, internal/namespaces/instance/v1/testdata/test-server-terminate-without-block.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-without-ip.cassette.yaml, internal/namespaces/instance/v1/testdata/test-server-terminate-without-ip.golden
=> fix(instance): delete sbs volumes on instance termination

internal/namespaces/instance/v1/helpers_types.go
The function to get the End of Service date of a commercial type to display a warning if it's about to be deprecated was filtering results from the Product Catalog according to the `product` field. But the content of this field might change in the future, whereas the `offer_id` nested attribute will not, therefore we should use this field as a filter instead.
=> fix(instance): EoS warning: filter products list by offer_id

.github/workflows/announce.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/nightly.yml, .github/workflows/purge.yml, .github/workflows/unit-tests.yaml, .github/workflows/wasm.yml
=> chore: add permissions for github actions

README.md
=> docs(jobs): add serverless jobs automation tutorials to readme

internal/namespaces/instance/v1/custom_image_test.go, internal/namespaces/instance/v1/custom_snapshot_test.go, internal/namespaces/instance/v1/helpers_test.go, internal/namespaces/instance/v1/instance_cli_test.go, internal/namespaces/instance/v1/testdata/test-create-volume-bad-size-unit.cassette.yaml, internal/namespaces/instance/v1/testdata/test-create-volume-simple.cassette.yaml, internal/namespaces/instance/v1/testdata/test-image-update-add-extra-volume.cassette.yaml, internal/namespaces/instance/v1/testdata/test-image-update-add-extra-volume.golden, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-name.cassette.yaml, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-name.golden, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-tags.cassette.yaml, internal/namespaces/instance/v1/testdata/test-update-snapshot-simple-change-tags.golden
Some tests from the Instance scope were still using deprecated `b_ssd` volumes, therefore they could not be recorded anymore. This PR changes all remaining occurrences to use `l_ssd` instead and has to be merged before any other change to the cassette system or the tests can be made.
=> tests(instance): replace remaining b_ssd volumes by l_ssd

go.mod, go.sum
=> fix: bump sdk-go to enable the new custom transport interface

go.mod, go.sum, internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.cassette.yaml, internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.golden, internal/namespaces/k8s/v1/testdata/test-wait-cluster-wait-for-pools.cassette.yaml, internal/namespaces/k8s/v1/testdata/test-wait-cluster-wait-for-pools.golden, internal/namespaces/vpc/v2/custom_private_network.go
Now that the `TryDeletingPrivateNetwork` function is available in the [sdk-go](https://github.com/scaleway/scaleway-sdk-go/pull/2660) we should remove the duplicate.
=> chore(vpc): use TryDeletingPrivateNetwork function from the sdk-go

internal/namespaces/instance/v1/custom_image.go
#4766 introduced a bug by getting snapshots using the zone of the volume, but this field is not present for SBS snapshots in the instance API. 
We should use the zone of the image instead.
=> fix(instance): snapshot list: get snapshot using image.Zone

cmd/scw/testdata/test-all-usage-webhosting-hosting-create-usage.golden, cmd/scw/testdata/test-all-usage-webhosting-hosting-list-usage.golden, docs/commands/webhosting.md, go.mod, go.sum, internal/namespaces/webhosting/v1/webhosting_cli.go
=> feat(webhosting): add hosting updating status and free subdomain support
