- README.md
- api/helpers.go
- commands/run.go
- main.go
> Refactored logging for 'scw run' (Fix #83)

- .travis.yml
- README.md
Not sure travis is already ready for Golang 1.5
> Bump to Golang 1.5

- .travis.yml
See: https://travis-ci.org/scaleway/scaleway-cli/jobs/80991009#L220
> Disable go1.4 testing

- pkg/api/api.go
> Refactor API

- .travis.yml
- pkg/commands/command_test.go
- pkg/commands/create_test.go
- pkg/commands/history_test.go
- pkg/commands/images_test.go
- pkg/commands/inspect_test.go
- pkg/commands/run_test.go
- pkg/commands/search_test.go
- pkg/commands/version_test.go
- pkg/sshcommand/sshcommand_test.go
> Fix tests on go@1.4

- README.md
- pkg/cli/cmd_run.go
- pkg/commands/run.go
> Support of `scw run --userdata=...`

- README.md
- pkg/cli/cmd_ps.go
- pkg/commands/ps.go
> Add arch filter "scw ps"

- README.md
- examples/create-image-from-http.sh
> create-image-from-http.sh: using VPS instead of C1 (fix #301)

- README.md
- pkg/api/api.go
Add hypervisor and cluster fields for VPS location
> Location VPS

- README.md
- pkg/cli/x_userdata.go
> _userdata: multiple '='

- README.md
- pkg/api/api.go
- pkg/api/cache.go
> Add a new field in the cache to handle UUID marketplace

- README.md
- pkg/cli/x_userdata.go
> _userdata: handle ~

- pkg/utils/utils.go
> handle piped command

- README.md
- pkg/commands/login.go
- pkg/sshcommand/sshcommand.go
> Windows compatibility

- README.md
- pkg/api/api.go
- pkg/api/helpers.go
> Invalid error message

- .gitignore
- README.md
- pkg/cli/cmd_run.go
- pkg/cli/cmd_start.go
- pkg/commands/run.go
- pkg/commands/start.go
> add --set-state

- README.md
- pkg/api/api.go
- pkg/commands/ps.go
> sort the servers by CreationDate

- README.md
- pkg/api/helpers.go
> Better handling of secondary volumes size

- pkg/api/api.go
This is a fix for the issue #410
> Fix #410: fix detection of paginated response

- pkg/cli/x_patch.go
> :bug: fix panic scw _patch security-group

- README.md
- pkg/api/helpers.go
- pkg/cli/cmd_create.go
- pkg/cli/cmd_run.go
- pkg/commands/create_test.go
- pkg/commands/run_test.go
Add two new offers:
- `X64-120G`
- `X64-120G`
Also rename of the `VC1*` to `X64-<size>`
> Add new commercial type

- README.md
- pkg/api/helpers.go
- pkg/cli/cmd_create.go
- pkg/cli/cmd_run.go
> Add two new offers X64-15GB and X64-30GB

- pkg/api/README.md
> api: Update README.md

- .gitignore
- vendor/github.com/moby/moby/pkg/term/termios_bsd.go
- vendor/github.com/moby/moby/pkg/term/windows/ansi_reader.go
- vendor/github.com/moby/moby/pkg/term/windows/ansi_writer.go
- vendor/github.com/moby/moby/pkg/term/windows/console.go
- vendor/github.com/moby/moby/pkg/term/windows/windows.go
- vendor/github.com/moby/moby/pkg/term/windows/windows_test.go
- vendor/vendor.json
**What i have done :**
+ Fixed the Moby term package to restore the `netbsd` compatibility. More info [here](https://github.com/moby/moby/pull/36887).
+ Then updating the package with `govendor`
+ Adding .DS_STORE in `.gitignore`
> Fix netbsd build

- pkg/commands/create_test.go
Wily image is not available anymore.
> Use xenial image for tests

- vendor/github.com/moul/gotty-client/LICENSE.apache
- vendor/github.com/moul/gotty-client/README.md
- vendor/github.com/moul/gotty-client/arch.go
- vendor/github.com/moul/gotty-client/gotty-client.go
- vendor/github.com/moul/gotty-client/proxy.go
- vendor/vendor.json
Fix #497 
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
> Bump gotty-client dependencies

- pkg/api/api.go
- pkg/cli/x_security-groups.go
- pkg/cli/x_security-groups_test.go
This add the field for stateful security groups
> Add security group stateful flags

- README.md
- contrib/completion/bash/scw.bash
- pkg/cli/cmd_ps.go
> fix: add stopped in place in ps command usage

- README.md
This PR adds information regarding the automatically built Chocolatey package for Windows users.
I've updated the chocolatey package to automatically update the package, so I think it's ready for prime time
> Add reference to Chocolatey package

- README.md
- pkg/cli/cmd_stop.go
I believe `scw wait server` was intended instead of `stop wait server` :wink: 
(Hopefully this is the right way to do a pull request, total newbie in this tool/project)
> Small typo in "scw stop" documentation

- .travis.yml
- README.md
- cmd/scw/main_unsupported.go
- goversion.go
- goversion_unsupported.go
In anticipation of the Go 1.13 support.
> feat: drop go@1.10 support

- contrib/completion/bash/scw.bash
> fix: only use noquote when it is supported

- README.md
- pkg/api/helpers.go
- pkg/cli/cmd_exec.go
- pkg/cli/cmd_run.go
- pkg/commands/exec.go
- pkg/commands/logs.go
- pkg/commands/port.go
- pkg/commands/run.go
- pkg/utils/utils.go
> feat(exec): add a no-tty flag

- internal/namespaces/instance/v1/custom_marshal.go
```
$ scw instance security-group create name=test01
security-group.id                       e15086e8-4937-4d27-bedf-2f50261d8ff4
security-group.name                     test01
security-group.description
security-group.enable-default-security  true
security-group.inbound-default-policy   accept
security-group.outbound-default-policy  accept
security-group.organization             14d2f7ae-9775-414c-9bed-6810e060d500
security-group.organization-default     false
security-group.creation-date            now
security-group.modification-date        now
security-group.servers                  0
security-group.stateful                 true
$ scw instance security-group create name=test01 …
```
> feat(intance): marshal create response

- internal/namespaces/instance/v1/custom_marshal.go
- Add `stateful` field
- Rename `use-by-default` field to `organization-default`
> feat(instance): improve security-group get output

- CONTRIBUTING.md
> chore: document commands notation validation

- internal/args/errors.go
- internal/args/marshal.go
- internal/args/unmarshal.go
- internal/args/unmarshal_test.go
> chore: return typed error in arg package

- internal/args/errors.go
- internal/args/marshal.go
- internal/args/marshal_test.go
- internal/args/unmarshal.go
- internal/core/cobra_utils.go
- internal/namespaces/instance/v1/command_server_create_test.go
- internal/namespaces/instance/v1/instance_cli_test.go
- internal/namespaces/instance/v1/testdata/test-create-volume-bad-size-unit.stderr.golden
- internal/namespaces/instance/v1/testdata/test-create-volume-simple.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-create-volume-simple.stdout.golden
> feat(core): bad size unit error

- internal/core/testing.go
- internal/namespaces/instance/v1/custom_server_create_test.go
- internal/namespaces/instance/v1/custom_server_test.go
- internal/namespaces/instance/v1/custom_user_data_test.go
- internal/namespaces/instance/v1/helpers_test.go
- internal/namespaces/instance/v1/instance_cli_test.go
- internal/namespaces/instance/v1/testdata/test-get-server-simple.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-get-server-simple.stdout.golden
- internal/namespaces/instance/v1/testdata/test-server-update-no-initial-placement-group&-placement-group-id=none.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-update-simple.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-update-simple.stdout.golden
> test(core): implement {Before|After}FuncCombine

- go.mod
- go.sum
> chore(core): bump sdk version

- cmd/scw/main_test.go
- internal/core/bootstrap_test.go
- internal/core/build_info_test.go
- internal/core/testing.go
- internal/e2e/errors_test.go
- internal/e2e/human_test.go
- internal/e2e/sdk_errors_test.go
- internal/human/marshal.go
- internal/human/marshal_func.go
- internal/namespaces/instance/v1/custom_server_create_test.go
- internal/namespaces/instance/v1/custom_server_test.go
- internal/namespaces/instance/v1/testdata/test-server-delete-only-block-volumes.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-delete-only-block-volumes.stderr.golden
- internal/namespaces/instance/v1/testdata/test-server-delete-only-local-volumes.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-delete-only-local-volumes.stderr.golden
- internal/namespaces/instance/v1/testdata/test-server-update-custom-volumes-detach-all-volumes.cassette.yaml
Tests were not run in parallel :sweat_smile: 
Fixes #764 
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>
> fix(core): fix parallel tests not being parallel

- cmd/scw/testdata/test-all-usage-instance-security-group-update-usage.stderr.golden
- internal/namespaces/instance/v1/custom_security_group.go
…y optional in update security-group
> fix(instance): make inbound and outbound default-policy optional in update security-group

- internal/namespaces/k8s/v1/custom_kubeconfig_install.go
> fix: typo in kubeconfig generation

- scripts/release/release.js
> chore: fix release script

- internal/core/result.go
> feat(core): add standard success message templates

- internal/core/command_interceptor.go
- internal/core/error.go
> refacto: handle sdk error with interecptor

- internal/core/command_interceptor.go
- internal/e2e/testdata/test-sdk-standard-errors-invalid-arguments.stderr.golden
- internal/namespaces/baremetal/v1alpha1/custom_server_test.go
- internal/namespaces/baremetal/v1alpha1/helpers_test.go
- internal/namespaces/instance/v1/testdata/test-server-update-no-initial-placement-group&-placement-group-id=invalid-pg-id.stderr.golden
> fix(core): fix some errors messages and tests

- internal/core/client.go
> fix(core): change profile flag precedence

- internal/namespaces/instance/v1/custom_server_test.go
> fix(test): fix flaky tests

- internal/namespaces/k8s/v1/custom_kubeconfig_uninstall.go
> fix(k8s): fix uninstall with current context

- internal/core/result.go
- internal/core/result_test.go
> feat(core): add emtpy sucees result

- .dockerignore
> feat(core): add dockerignore

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/SUPPORT.md
- .github/pull_request_template.md
backport of 9eedf1f482568115732b3aa1fb2e6e331625227d
> doc: add issues, pull-requests templates and support documentation

- internal/namespaces/k8s/v1/custom_kubeconfig_install.go
> fix(k8s): fix typo in arg name

- internal/core/build_info_test.go
- internal/core/cobra_utils.go
- internal/core/cobra_utils_test.go
- internal/core/command.go
- internal/namespaces/autocomplete/autocomplete.go
- internal/namespaces/config/commands.go
- internal/namespaces/feedback/custom.go
- internal/namespaces/init/init.go
- internal/namespaces/version/version.go
Closes https://github.com/scaleway/scaleway-cli/issues/968
> chore: rename core.Command `NoClient` to `AllowAnnonymousClient` 

- cmd/scw/testdata/test-all-usage-instance-snapshot-create-usage.stderr.golden
- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_snapshot.go
> feat(instance): add wait flag on create snapshot

- cmd/scw/testdata/test-all-usage-instance-image-usage.stderr.golden
- cmd/scw/testdata/test-all-usage-instance-image-wait-usage.stderr.golden
- cmd/scw/testdata/test-all-usage-instance-snapshot-usage.stderr.golden
- cmd/scw/testdata/test-all-usage-instance-snapshot-wait-usage.stderr.golden
- internal/namespaces/instance/v1/custom.go
- internal/namespaces/instance/v1/custom_image.go
- internal/namespaces/instance/v1/custom_snapshot.go
> feat(instance): add a wait command for image and snapshots

- cmd/scw/main.go
> chore: remove sentry from dev build

- internal/args/args.go
- internal/args/args_test.go
- internal/core/arg_specs.go
- internal/core/arg_specs_test.go
- internal/core/errors.go
- internal/core/validate.go
- internal/core/validate_test.go
> feat: add oneof group field and validation

- internal/namespaces/baremetal/v1alpha1/custom.go
- internal/namespaces/baremetal/v1alpha1/custom_server.go
- internal/namespaces/baremetal/v1alpha1/testdata/test-install-server-simple-with-id.stdout.golden
- internal/namespaces/baremetal/v1alpha1/testdata/test-list-server-simple.stdout.golden
> feat(baremetal): add a custom enum marshaling for ping status

- internal/namespaces/registry/v1/custom.go
- internal/namespaces/registry/v1/custom_image.go
- internal/namespaces/registry/v1/custom_tag.go
> feat(registry): add full name support for tag and list on list and get

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_security_group.go
- internal/namespaces/instance/v1/custom_server.go
> chore: remove dependency on github.com/hashicorp/go-multierror

- internal/sentry/sentry.go
> fix: use correct sentry DSN

- internal/qa/ignore.go
> test(qa): add ignore error filtering

- cmd/scw/testdata/test-all-usage-instance-volume-update-usage.stderr.golden
- go.mod
- go.sum
- internal/namespaces/k8s/v1/testdata/test-get-kubeconfig-simple.cassette.yaml
- internal/namespaces/k8s/v1/testdata/test-install-kubeconfig-merge.cassette.yaml
- internal/namespaces/k8s/v1/testdata/test-install-kubeconfig-simple.cassette.yaml
- internal/namespaces/k8s/v1/testdata/test-uninstall-kubeconfig-empty-file.cassette.yaml
- internal/namespaces/k8s/v1/testdata/test-uninstall-kubeconfig-uninstall-merge.cassette.yaml
- internal/namespaces/k8s/v1/testdata/test-uninstall-kubeconfig-uninstall.cassette.yaml
> chore(vendor): update sdk

- scripts/release/release.js
> chore(release): add docker build and push from the release script

- cmd/scw/main.go
> chore: cleanup after v2.0.0-beta.3 release

- internal/core/testing.go
- internal/namespaces/registry/v1/custom_image_test.go
- internal/namespaces/registry/v1/testdata/test-image-list-simple.cassette.yaml
- internal/namespaces/registry/v1/testdata/test-image-list-simple.stdout.golden
> test(registry): fix registry visibility problems

- internal/account/test.go
> fix(init): fix panic

- scripts/release/release.js
> chore(release_script): remove unused files

- scripts/release.sh
> chore(release): manage vault secret from release script

- .github/stale.yml
We will need to enable it once it is merged in the default branch of the repository https://github.com/apps/stale
> feat: add a stale bot configuration

- internal/namespaces/autocomplete/autocomplete.go
- internal/namespaces/autocomplete/errors.go
> feat: improve error message in autocomplete install

- scripts/build.sh
- scripts/release/release.js
> feat: add support for windows and linux i386 (32bits)

- README.md
> doc: add a link to v1 branch on README

- go.mod
- go.sum
- internal/core/arg_specs.go
- internal/namespaces/account/v2alpha1/testdata/test-ssh-key-add-command-simple.golden
```release-note
- validate zone and region arguments
```
> fix: improve validation of zone and region args

- internal/gofields/gofields.go
- internal/gofields/gofields_test.go
> chore: add gofield utility package

- internal/core/testing.go
- internal/tabwriter/tabwriter_test.go
- scripts/run-tests.sh
> chore(scripts): exclude os specific goldens from removal when updating

- internal/core/testdata/test-positional-arg-multi-positional.golden
- internal/e2e/testdata/test-human-create-simple.golden
- internal/e2e/testdata/test-human-create-with-args.golden
- internal/e2e/testdata/test-human-delete-simple.golden
- internal/e2e/testdata/test-human-get-simple.golden
- internal/e2e/testdata/test-human-update-multiple-args.golden
- internal/e2e/testdata/test-human-update-single-arg.golden
- internal/human/marshal.go
- internal/human/marshal_test.go
- internal/namespaces/account/v2alpha1/testdata/test-ssh-key-add-command-simple.golden
- internal/namespaces/baremetal/v1/testdata/test-create-server-simple-default.golden
- internal/namespaces/baremetal/v1/testdata/test-install-server-simple-all-ssh-keys.golden
- internal/namespaces/baremetal/v1/testdata/test-install-server-simple-with-id.golden
- internal/namespaces/feedback/custom_test.go
- internal/namespaces/feedback/testdata/test-feedback-bug-simple.golden
- internal/namespaces/feedback/testdata/test-feedback-feature-simple.golden
- internal/namespaces/info/custom.go
- internal/namespaces/info/testdata/test-info-show-secret.golden
- internal/namespaces/info/testdata/test-info-simple.golden
- internal/namespaces/instance/v1/custom_server.go
- internal/namespaces/instance/v1/testdata/test-create-server-simple-default.golden
- internal/namespaces/instance/v1/testdata/test-get-server-simple.golden
- internal/namespaces/instance/v1/testdata/test-image-create-create-simple-image.golden
- internal/namespaces/instance/v1/testdata/test-image-create-use-additional-snapshots.golden
- internal/namespaces/instance/v1/testdata/test-ip-create-simple.golden
- internal/namespaces/instance/v1/testdata/test-ip-get-simple.golden
- internal/namespaces/instance/v1/testdata/test-ip-update-simple.golden
- internal/namespaces/instance/v1/testdata/test-server-backup-simple.golden
- internal/namespaces/instance/v1/testdata/test-server-update-simple.golden
- internal/namespaces/instance/v1/testdata/test-snapshot-create-simple.golden
> chore: human printer use Go format instead of bash for struct field name

- cmd/scw/testdata/test-all-usage-rdb-instance-clone-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-instance-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-instance-wait-usage.golden
- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_instance.go
- internal/namespaces/rdb/v1/custom_instance_clone.go
- internal/namespaces/rdb/v1/custom_instance_clone_test.go
- internal/namespaces/rdb/v1/custom_instance_create.go
- internal/namespaces/rdb/v1/custom_instance_create_test.go
- internal/namespaces/rdb/v1/custom_instance_upgrade.go
- internal/namespaces/rdb/v1/custom_instance_upgrade_test.go
- internal/namespaces/rdb/v1/testdata/test-clone-instance-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-clone-instance-simple.golden
- internal/namespaces/rdb/v1/testdata/test-create-instance-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-create-instance-simple.golden
- internal/namespaces/rdb/v1/testdata/test-upgrade-instance-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-upgrade-instance-simple.golden
> rdb: add wait function to create instance and as a verb

- go.sum
- internal/core/bootstrap.go
- internal/core/build_info.go
- internal/core/build_info_test.go
- internal/core/client.go
- internal/core/cobra_utils.go
- internal/core/context.go
- internal/core/testdata/test-check-version-already-checked.golden
- internal/core/testdata/test-check-version-check-more-than24h-ago.cassette.yaml
- internal/core/testdata/test-check-version-outdated-version.cassette.yaml
- internal/core/testdata/test-check-version-outdated-version.golden
- internal/core/testdata/test-check-version-up-to-date-version.cassette.yaml
- internal/core/testdata/test-check-version-up-to-date-version.golden
- internal/core/testing.go
- internal/namespaces/feedback/custom_test.go
- internal/namespaces/feedback/testdata/test-feedback-bug-simple.golden
- internal/namespaces/feedback/testdata/test-feedback-feature-simple.golden
- internal/namespaces/info/testdata/test-info-show-secret.golden
- internal/namespaces/info/testdata/test-info-simple.golden
> test: fix test on new version warning

- cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-instance-upgrade-usage.golden
- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_instance_clone_test.go
- internal/namespaces/rdb/v1/custom_instance_create.go
- internal/namespaces/rdb/v1/custom_instance_create_test.go
- internal/namespaces/rdb/v1/custom_instance_upgrade.go
- internal/namespaces/rdb/v1/custom_instance_upgrade_test.go
- internal/namespaces/rdb/v1/testdata/test-clone-instance-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-create-instance-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-upgrade-instance-simple.cassette.yaml
> rdb: add default for node-types values

- cmd/scw/testdata/test-all-usage-config-set-usage.golden
- internal/core/errors.go
- internal/namespaces/config/commands.go
> feat(config): add support for default-project-id in config set

- internal/namespaces/rdb/v1/custom_instance.go
- internal/namespaces/rdb/v1/testdata/test-clone-instance-simple.golden
- internal/namespaces/rdb/v1/testdata/test-create-instance-simple.golden
- internal/namespaces/rdb/v1/testdata/test-get-instance-simple.golden
- internal/namespaces/rdb/v1/testdata/test-upgrade-instance-simple.golden
> fix(rdb): fix human marshaler for rdb BackupSchedule

- internal/args/args_test.go
- internal/args/marshal.go
- internal/args/marshal_test.go
- internal/args/unmarshal.go
- internal/args/unmarshal_test.go
> core: add parsing for absolute time.Time

- go.mod
- go.sum
> chore: update sdk

- go.mod
- go.sum
> chore: bump sdk version

- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_backup.go
- internal/namespaces/rdb/v1/custom_instance.go
- internal/namespaces/rdb/v1/custom_log.go
> rdb: add color rendering for status

- .github/workflows/unit-tests.yaml
> chore: remove verbose option in the tests

- internal/namespaces/instance/v1/custom_server_create.go
- internal/namespaces/instance/v1/custom_server_create_test.go
- internal/namespaces/instance/v1/testdata/test-create-server-simple-with-bootscript.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-create-server-simple-with-start.cassette.yaml
> fix(instance): boot_type mode  on create server

- README.md
> docs: add a warning message to CLIv1 readme

- README.md
> fix: fix readme broken images

- internal/core/testing.go
- internal/namespaces/rdb/v1/custom_instance_test.go
> chore: add helper to store directly values in Meta

- docs/cookbook.md
> doc: add cookbook file

- docs/cookbook.md
> doc: fix typo

- internal/human/marshal_func.go
> core: add coloring for boolean values

- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_lbtypes.go
> feat(lb): add human marshalling for lb-types stocks

- cmd/scw/testdata/test-all-usage-lblb-create-usage.golden
- cmd/scw/testdata/test-all-usage-lblb-usage.golden
- cmd/scw/testdata/test-all-usage-lblb-wait-usage.golden
- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_lb.go
- internal/namespaces/lb/v1/custom_lb_test.go
- internal/namespaces/lb/v1/helper_test.go
- internal/namespaces/lb/v1/testdata/test-create-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-create-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-get-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-get-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-list-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-list-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-wait-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-wait-lb-simple.golden
> feat(lb): add support for wait in lb create and wait verb

- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_acl.go
> feat(lb): add human marshaller for acl accept/deny

- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_certificate.go
> feat(lb): add human marshalling for certificate status

- cmd/scw/testdata/test-all-usage-lblb-create-usage.golden
- cmd/scw/testdata/test-all-usage-lblb-migrate-usage.golden
- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_lb.go
- internal/namespaces/lb/v1/helper_test.go
- internal/namespaces/lb/v1/testdata/test-create-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-create-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-get-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-get-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-list-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-list-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-wait-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-wait-lb-simple.golden
> lb: add enumvalues for lb migration

- internal/namespaces/instance/v1/custom.go
- internal/namespaces/instance/v1/custom_user_data.go
- internal/namespaces/instance/v1/custom_user_data_test.go
- internal/namespaces/instance/v1/testdata/test-user-data-list-simple.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-user-data-list-simple.golden
> feat(instance): add human marshalling for user-data

- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_acl.go
- internal/namespaces/rdb/v1/custom_node_type.go
> feat(rdb): add coloring for node-type availability and acl action

- internal/namespaces/instance/v1/custom_user_data.go
> chore: fix flaky user data test

- cmd/scw/testdata/test-all-usage-baremetal-server-start-usage.golden
- go.mod
- go.sum
- internal/namespaces/lb/v1/testdata/test-create-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-create-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-get-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-get-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-list-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-list-lb-simple.golden
- internal/namespaces/lb/v1/testdata/test-wait-lb-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-wait-lb-simple.golden
Fix cassettes for LB
```release-note
```
> chore: bump sdk

- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_lb.go
> feat(lb): add human marshaller for LBStatus

- README.md
> doc: fix READMEv1

- internal/args/unmarshal.go
- internal/args/unmarshal_test.go
> feat(core): add support for net.IP unmarshal

- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_acl.go
- internal/namespaces/rdb/v1/custom_acl_test.go
- internal/namespaces/rdb/v1/testdata/test-add-acl-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-add-acl-simple.golden
- internal/namespaces/rdb/v1/testdata/test-delete-acl-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-delete-acl-simple.golden
> feat(rdb): add nice human marshalling for add/delete rules

- internal/human/marshal_func.go
- internal/human/marshal_test.go
- internal/namespaces/rdb/v1/testdata/test-create-backup-simple.golden
- internal/namespaces/rdb/v1/testdata/test-export-backup-simple.golden
- internal/namespaces/rdb/v1/testdata/test-restore-backup-simple.golden
> fix(human): marshalling size ptr

- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_frontend.go
- internal/namespaces/lb/v1/custom_frontend_test.go
- internal/namespaces/lb/v1/testdata/test-get-frontend-simple.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-get-frontend-simple.golden
> feat(lb): add human marshaller for frontend

- cmd/scw/testdata/test-all-usage-instance-user-data-delete-usage.golden
- cmd/scw/testdata/test-all-usage-instance-user-data-get-usage.golden
- cmd/scw/testdata/test-all-usage-instance-user-data-set-usage.golden
- internal/namespaces/instance/v1/custom_user_data.go
- internal/namespaces/instance/v1/custom_user_data_test.go
- internal/namespaces/instance/v1/testdata/test-user-data-get-get-an-existing-key.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-user-data-get-get-an-nonexistent-key.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-user-data-list-simple.cassette.yaml
> feat(instance): remove positional server-id in delete/set/get user-data

- .github/workflows/unit-tests.yaml
- cmd/scw/testdata/test-all-usage-help-output-usage.golden
- cmd/scw/testdata/test-all-usage-help-usage.golden
- cmd/scw/testdata/test-main-usage-usage.golden
- internal/namespaces/get_commands.go
- internal/namespaces/help/custom.go
- internal/namespaces/help/output.go
> doc: add an help output command

- cmd/scw/testdata/test-all-usage-lb-certificate-create-usage.golden
- internal/core/printer_test.go
- internal/core/testing.go
- internal/namespaces/lb/v1/custom.go
- internal/namespaces/lb/v1/custom_certificate.go
- internal/namespaces/lb/v1/custom_certificate_test.go
- internal/namespaces/lb/v1/testdata/test-create-certificate-import.cassette.yaml
- internal/namespaces/lb/v1/testdata/test-create-certificate-import.golden
> feat(lb): simplify argument passing for certificate creation

- internal/human/marshal.go
> fix(core): handle empty slice marshalling

- internal/namespaces/lb/v1/custom_lb.go
> chore: add retry interval to lb

- internal/human/marshal.go
- internal/human/marshal_test.go
- internal/namespaces/instance/v1/custom_placement_group.go
- internal/namespaces/instance/v1/custom_placement_group_test.go
- internal/namespaces/instance/v1/testdata/test-get-placement-group-simple.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-get-placement-group-simple.golden
> fix(marshal): fix human marshal on edge cases

- internal/gotty/client.go
> fix(gotty): use new URLs

- internal/core/arg_specs.go
> chore(core): add a ProjectArgSpec

- internal/namespaces/instance/v1/custom.go
- internal/namespaces/instance/v1/custom_server.go
- internal/namespaces/instance/v1/testdata/test-get-server-simple.golden
> feat(vpc): add support to visualize private nic from instance get server

- internal/human/marshal.go
- internal/namespaces/baremetal/v1/testdata/test-list-server-list-with-tags.golden
- internal/namespaces/baremetal/v1/testdata/test-list-server-simple.golden
> chore(human): always print header line in empty list

- cmd/scw/main_test.go
> test: enable parallel execution in all usage testing

- scripts/release.sh
> chore: add docker login in release script

- README.md
> doc: add brew to readme

- .github/workflows/codeql-analysis.yml
> chore: create codeql-analysis.yml

- internal/namespaces/instance/v1/custom_server.go
> fix(instance): use args zone on vpc call

- internal/namespaces/registry/v1/custom_docker_helper_test.go
> chore: fix typos

- README.md
This adds back the Cocolatey package manager note.
```release-note
```
> Add back Chocolatey.

- README.md
> doc: add AUR link to README

- internal/namespaces/instance/v1/custom_server_create.go
> doc(instance): remove outdated TODOs in create_server

- internal/namespaces/k8s/v1/custom_cluster.go
- internal/namespaces/k8s/v1/testdata/test-get-cluster-simple.golden
> fix(k8s): fix k8s get json output

- scripts/build.sh
> fix(scripts): use dots instead of dashes in binary name version

- internal/namespaces/instance/v1/custom_server_type.go
- internal/namespaces/instance/v1/testdata/test-server-type-list-server-type-list.golden
> feat(instance): remove monthly prices from server types list

- cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden
- internal/namespaces/instance/v1/custom_server_create.go
> chore(instance): add support for STARDUST1-S autocomplete

- .github/workflows/golangci-lint.yml
> chore: bump golangci-lint

- .github/CONTRIBUTING.md
- SECURITY.md
> doc: create the security policy

- internal/namespaces/instance/v1/custom_server_create.go
- internal/namespaces/instance/v1/custom_user_data.go
- internal/namespaces/instance/v1/testdata/test-user-data-get-get-an-nonexistent-key.golden
- internal/namespaces/k8s/v1/custom_kubeconfig_uninstall.go
- internal/namespaces/registry/v1/custom_docker_helper.go
Signed-off-by: Amine Kherbouche <akherbouche@scaleway.com>
```release-note
```
> chore(typo): fix typo

- internal/namespaces/instance/v1/custom_image.go
- internal/namespaces/instance/v1/testdata/test-image-list-simple.golden
> fix(instance): use snake case in json output format for image list

- internal/namespaces/k8s/v1/custom.go
- internal/namespaces/k8s/v1/custom_version.go
- internal/namespaces/k8s/v1/custom_version_test.go
- internal/namespaces/k8s/v1/testdata/test-get-version-simple.cassette.yaml
- internal/namespaces/k8s/v1/testdata/test-get-version-simple.golden
- internal/namespaces/k8s/v1/testdata/test-list-version-basic-simple.cassette.yaml
- internal/namespaces/k8s/v1/testdata/test-list-version-basic-simple.golden
> feat(k8s): fix version list and add a golden test

- cmd/scw/testdata/test-all-usage-k8s-pool-create-usage.golden
- internal/namespaces/k8s/v1/custom_pool.go
> feat(k8s): add default node type and size in create pool

- internal/namespaces/lb/v1/custom_lb.go
> feat(lb): allow all types

- internal/namespaces/instance/v1/custom_server_create.go
> feat(instance): add support for instances with no local volumes reqs

- internal/namespaces/domain/v2beta1/custom.go
- internal/namespaces/domain/v2beta1/custom_certificate.go
> dns: add support for enum marshall status for certificate

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom.go
- internal/namespaces/instance/v1/custom_privatenics.go
- internal/namespaces/instance/v1/custom_security_group.go
- internal/namespaces/instance/v1/custom_volume.go
- internal/namespaces/instance/v1/testdata/test-list-ni-cs-simple.golden
> feat: update scaleway sdk

- internal/namespaces/k8s/v1/custom_kubeconfig_install.go
> fix kubeconfig install command

- .github/dependabot.yml
> chore: add support for dependabot

- README.md
> docs: add references to lb and vpc commands in the README

- cmd/scw/testdata/test-all-usage-instance-server-update-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom_server.go
> feat(instance): cleanup organization and project from volume

- cmd/scw/testdata/test-all-usage-baremetal-server-create-usage.golden
- docs/commands/baremetal.md
- internal/namespaces/baremetal/v1/custom_server_create.go
- internal/namespaces/baremetal/v1/custom_server_create_test.go
> fix(baremetal): Remove baremetal old type

- internal/namespaces/instance/v1/custom_server_create.go
> feat(instance): send the VolumeType for the root-volume when it's set by the user

- cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom_server_create.go
> feat(instance): add support for pro2

- cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom_server_create.go
> feat(instance): add support for play instance

- cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom_server_create.go
> feat(instance): add support for GPU-3070-S

- internal/namespaces/baremetal/v1/custom_server_create.go
> feat(baremetal): add support for install in the create command

- README.md
> docs: fix go install documentation

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_security_group.go
- internal/namespaces/instance/v1/testdata/test-snapshot-create-simple.golden
- internal/namespaces/lb/v1/testdata/test-get-frontend-simple.golden
- internal/namespaces/rdb/v1/testdata/test-list-instance-simple.golden
> bump: sdk-go with fix custom_security_group type and update goldens

- README.md
> docs(README): update to 2.5.4 as latest release

- internal/namespaces/iam/v1alpha1/custom.go
> feat(iam): auto-complete permission-set names

- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_backup.go
- internal/namespaces/rdb/v1/custom_backup_test.go
- internal/namespaces/rdb/v1/testdata/test-list-backup-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-list-backup-simple.golden
> feat(rdb): add a boolean to reveal if a backup is exported

- internal/namespaces/rdb/v1/custom_backup.go
- internal/namespaces/rdb/v1/custom_backup_test.go
- internal/namespaces/rdb/v1/testdata/test-download-backup-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-download-backup-with-no-previous-export-backup.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-download-backup-with-no-previous-export-backup.golden
> feat(rdb): add to backup download an export step in case that was not done before

- cmd/scw/testdata/test-all-usage-help-output-usage.golden
- docs/commands/help.md
- internal/core/printer.go
- internal/human/marshal.go
- internal/human/specs.go
- internal/namespaces/help/output.go
> feat(printer): add wide output

- internal/namespaces/instance/v1/custom_server_create.go
> feat(instance): cache image auto complete result

- internal/core/command.go
> fix(core): command remove out of bound

- internal/core/validate.go
close #1494
Deprecated argument were logged even when not used.
> fix(core/validate): log deprecated arg only when used

- internal/core/testing.go
> feat(testing): validate json goldens

- internal/human/utils.go
- internal/namespaces/config/testdata/test-config-destroy-command-check-config-file.golden
- internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-image-label.golden
- internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-instance-type.golden
> fix(human): skip capitalize on uuid

- internal/args/unmarshal.go
> feat(unmarshal): parse time.Duration

- internal/core/shell.go
- internal/core/shell_disabled.go
> fix(shell): disable shell on freebsd

- internal/namespaces/domain/v2beta1/custom_record_delete.go
> fix(domain_record): output request response

- .github/workflows/unit-tests.yaml
- cmd/scw/main.go
> ci: bump go version

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_snapshot.go
> chore: bump sdk-go

- internal/core/arg_file_content.go
> fix(core): crash on missing field that support file loading

- cmd/scw/testdata/test-all-usage-iot-hub-create-usage.golden
- internal/namespaces/iot/v1/custom.go
- internal/namespaces/iot/v1/custom_hub.go
- internal/namespaces/iot/v1/custom_network.go
- internal/namespaces/iot/v1/custom_network_test.go
- internal/namespaces/iot/v1/helper_test.go
- internal/namespaces/iot/v1/testdata/test-create-network-simple.cassette.yaml
- internal/namespaces/iot/v1/testdata/test-create-network-simple.golden
> feat(iot): improve network create output

- internal/core/cobra_builder.go
- internal/core/cobra_usage_builder.go
> perf(core): lazy load usage

- internal/core/cobra_builder.go
> perf(core): lazy load usage annotations allocation

- internal/core/cobra_builder.go
- internal/core/cobra_usage_builder.go
> perf(core): cobra builder allocate with nb of commands and use unordered list

- .github/workflows/release.yml
> ci: add homebrew bump formulae workflow

- internal/human/marshal_func.go
> feat(core): add scw.JSONObject marshaler

- cmd/scw/testdata/test-all-usage-instance-server-create-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom_server_create.go
> fix(instance): add ENT1-XS and ENT1-XXS to the CLI

- internal/core/shell.go
Closes #2736 
```release-note
shell: use a space-terminated prompt
```
> feat(shell): use a space-terminated prompt

- README.md
> fix(docs): add vpc gateway documentation path

- internal/core/testing.go
- internal/namespaces/config/commands_test.go
- internal/namespaces/config/testdata/test-config-info-command-profile.golden
- internal/namespaces/config/testdata/test-config-info-command-simple.golden
> tests: golden regex replace only actual output

- README.md
> docs(tem): add reference documentation

- internal/args/unmarshal.go
- internal/args/unmarshal_test.go
> fix(args): none arg set slice ptr to an empty slice

- cmd/scw/testdata/test-all-usage-dns-zone-import-usage.golden
- internal/namespaces/domain/v2beta1/custom.go
> feat(dns): import dns zone using file path

- internal/namespaces/instance/v1/custom_server_create.go
- internal/namespaces/instance/v1/custom_server_create_test.go
> fix(instance): ignore bootscript deprecated lint error

- internal/namespaces/domain/v2beta1/custom.go
- internal/namespaces/domain/v2beta1/domain_cli.go
move defaultTTL const from generated domain_cli.go to custom.go
> fix(dns): move defaultTTL const

- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/unit-tests.yaml
> ci: add merge_group support

- docs/developer.md
- internal/core/bootstrap.go
> fix(core): logger level error as default when output is not human

- cmd/scw/testdata/test-all-usage-cockpit-cockpit-activate-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-cockpit-deactivate-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-cockpit-get-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-cockpit-reset-grafana-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-cockpit-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-cockpit-wait-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-grafana-user-create-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-grafana-user-delete-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-grafana-user-list-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-grafana-user-reset-password-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-grafana-user-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-token-create-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-token-delete-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-token-get-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-token-list-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-token-usage.golden
- cmd/scw/testdata/test-all-usage-cockpit-usage.golden
- cmd/scw/testdata/test-main-usage-usage.golden
- internal/namespaces/cockpit/v1beta1/custom.go
- internal/namespaces/cockpit/v1beta1/custom_cockpit.go
- internal/namespaces/get_commands.go
> feat(cockpit): enable and configure commands

- internal/core/autocomplete_utils.go
> fix(autocomplete): apply default values to list on arg completion

- internal/args/unmarshal.go
Fix #2840
Fix #2841 
Fix #2842
> fix(args): parse slice indexes as 32 bits

- cmd/scw/testdata/test-all-usage-secret-version-create-usage.golden
- docs/commands/secret.md
- internal/args/unmarshal.go
- internal/core/arg_file_content.go
- internal/human/marshal_func.go
- internal/human/marshal_test.go
- internal/namespaces/secret/v1alpha1/custom.go
> feat(secret): handle bytes data

- internal/core/arg_specs.go
- internal/core/arg_specs_test.go
- internal/core/reflect.go
> feat(core): add argspec util to get corresponding type from argstype

- internal/namespaces/cockpit/v1beta1/custom.go
- internal/namespaces/cockpit/v1beta1/custom_cockpit.go
> feat(cockpit): display token scopes separately

- internal/namespaces/cockpit/v1beta1/custom.go
- internal/namespaces/cockpit/v1beta1/custom_cockpit.go
> feat(cockpit): display endpoints separately

- README.md
> docs(cockpit): add in readme

- cmd/scw/testdata/test-all-usage-container-namespace-create-usage.golden
- cmd/scw/testdata/test-all-usage-container-namespace-delete-usage.golden
- docs/commands/container.md
- internal/core/errors_cmp.go
- internal/namespaces/container/v1beta1/custom.go
- internal/namespaces/container/v1beta1/custom_namespace.go
> feat(container): add namespace waiters

- docs/cookbook.md
> docs: add more example in cookbook

- cmd/scw/testdata/test-all-usage-instance-server-delete-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom_server.go
- internal/namespaces/instance/v1/custom_server_test.go
- internal/namespaces/instance/v1/testdata/test-server-delete-with-none-volumes.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-delete-with-none-volumes.golden
Also changed default to `all` as it was doing it since 2020
> fix(instance): delete with-volumes none worked like all

- internal/namespaces/function/v1beta1/custom_deploy.go
> fix(function): use default interval on deploy

- .golangci.yml
> chore: remove depguards from linters

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_server_type.go
- internal/namespaces/instance/v1/testdata/test-server-type-list-server-type-list.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-type-list-server-type-list.golden
> fix(instance): paginate server types availability

- cmd/scw/testdata/test-all-usage-instance-ssh-add-key-usage.golden
- cmd/scw/testdata/test-all-usage-instance-ssh-install-config-usage.golden
- cmd/scw/testdata/test-all-usage-instance-ssh-list-keys-usage.golden
- cmd/scw/testdata/test-all-usage-instance-ssh-remove-key-usage.golden
- docs/commands/instance.md
- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_server.go
- internal/namespaces/instance/v1/custom_server_create.go
Those changes with the new sdk fix issues with server's volume not updating some fields
> chore(instance): bump sdk-go with breaking changes

- cmd/scw/testdata/test-all-usage-account-project-create-usage.golden
- cmd/scw/testdata/test-all-usage-account-project-delete-usage.golden
- cmd/scw/testdata/test-all-usage-account-project-get-usage.golden
- cmd/scw/testdata/test-all-usage-account-project-list-usage.golden
- cmd/scw/testdata/test-all-usage-account-project-update-usage.golden
- cmd/scw/testdata/test-main-usage-usage.golden
- docs/commands/account.md
- internal/namespaces/account/v3/custom.go
- internal/namespaces/get_commands.go
- internal/namespaces/init/prompt.go
> feat(account): migrate to v3 api

- internal/namespaces/instance/v1/custom_ssh_config.go
- internal/sshconfig/sshconfig.go
> fix: fix direct error comparison

- .github/dependabot.yml
- go.mod
- go.sum
The latest versions does not work with our sentry
> fix: fix sentry version

- internal/namespaces/vpc/v2/custom.go
- internal/namespaces/vpc/v2/custom_private_network.go
- internal/namespaces/vpc/v2/custom_private_network_test.go
- internal/namespaces/vpc/v2/helper_test.go
- internal/namespaces/vpc/v2/testdata/test-get-private-network-multiple.cassette.yaml
- internal/namespaces/vpc/v2/testdata/test-get-private-network-multiple.golden
- internal/namespaces/vpc/v2/testdata/test-get-private-network-simple.cassette.yaml
- internal/namespaces/vpc/v2/testdata/test-get-private-network-simple.golden
> feat(vpc): make get private-network show all attached resources

- .github/workflows/wasm.yml
- wasm/.prettierignore
- wasm/.prettierrc
- wasm/cli.d.ts
- wasm/index.d.ts
- wasm/index.js
- wasm/package.json
- wasm/src/cli.test.ts
- wasm/src/jshelpers.test.ts
- wasm/src/utils.ts
- wasm/wasm_exec.cjs
- wasm/wasm_exec.d.ts
- wasm/wasm_exec_node.cjs
> chore: add support for prettier

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_server_create.go
- internal/namespaces/instance/v1/custom_server_create_test.go
- internal/namespaces/instance/v1/testdata/test-create-server-scratch-storage-default-scratch-storage.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-create-server-scratch-storage-default-scratch-storage.golden
> feat(instance): support scratch volumes in servers

- .github/workflows/wasm.yml
> ci(wasm): fix prettier step

- internal/namespaces/instance/v1/helpers_types.go
> feat(instance): add H100 server types

- cmd/scw/testdata/test-all-usage-ipfs-pin-create-by-cid-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-pin-create-by-url-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-pin-delete-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-pin-get-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-pin-list-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-volume-delete-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-volume-get-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-volume-list-usage.golden
- cmd/scw/testdata/test-all-usage-ipfs-volume-update-usage.golden
- docs/commands/ipfs.md
- internal/namespaces/ipfs/v1alpha1/ipfs_cli.go
> docs(ipfs): fix wording

- internal/namespaces/get_commands.go
- internal/namespaces/mnq/v1beta1/custom.go
- internal/namespaces/mnq/v1beta1/custom_sqs.go
> feat(mnq): enable v1beta1 commands

- .golangci.yml
- internal/qa/qa.go
> chore: fix lint goconst

- cmd/scw/testdata/test-main-usage-usage.golden
- internal/namespaces/ipfs/v1alpha1/custom.go
> feat(ipfs): add command ipns in labs commands

- cmd/scw/testdata/test-all-usage-instance-image-update-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom_image.go
- internal/namespaces/instance/v1/custom_image_test.go
> fix(instance): image update positional arg

- internal/namespaces/instance/v1/custom_image.go
> fix(instance): image update with invalid uuid

- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_instance.go
- internal/namespaces/rdb/v1/testdata/test-get-instance-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-get-instance-simple.golden
> feat(rdb): list ACLs when getting a rdb instance

- cmd/scw/testdata/test-all-usage-redis-cluster-create-usage.golden
- cmd/scw/testdata/test-all-usage-redis-cluster-usage.golden
- cmd/scw/testdata/test-all-usage-redis-cluster-wait-usage.golden
- docs/commands/redis.md
- internal/namespaces/redis/v1/custom.go
- internal/namespaces/redis/v1/custom_cluster.go
- internal/namespaces/redis/v1/custom_cluster_test.go
- internal/namespaces/redis/v1/testdata/test-endpoints-edge-cases-private-endpoint-with-both-attributes-set.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-endpoints-edge-cases-private-endpoint-with-both-attributes-set.golden
- internal/namespaces/redis/v1/testdata/test-endpoints-edge-cases-private-endpoint-with-none-set.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-endpoints-edge-cases-private-endpoint-with-none-set.golden
- internal/namespaces/redis/v1/testdata/test-endpoints-single-public-endpoint.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-endpoints-single-public-endpoint.golden
- internal/namespaces/redis/v1/testdata/test-endpoints-single-static-private-endpoint.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-endpoints-single-static-private-endpoint.golden
- internal/namespaces/redis/v1/testdata/test-endpoints-two-static-private-endpoints.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-endpoints-two-static-private-endpoints.golden
- internal/namespaces/redis/v1/testdata/test-ipam-config-both-ipam-and-static-private-endpoints.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-ipam-config-both-ipam-and-static-private-endpoints.golden
- internal/namespaces/redis/v1/testdata/test-ipam-config-single-ipam-private-endpoint.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-ipam-config-single-ipam-private-endpoint.golden
- internal/namespaces/redis/v1/testdata/test-ipam-config-two-ipam-private-endpoints.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-ipam-config-two-ipam-private-endpoints.golden
> feat(redis): ipam config for private endpoints

- internal/namespaces/instance/v1/custom_server.go
- internal/namespaces/instance/v1/custom_server_test.go
- internal/namespaces/instance/v1/testdata/test-server-delete-with-sbs-volumes.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-delete-with-sbs-volumes.golden
> fix(instance): server delete with sbs volumes

- internal/gotty/client.go
> feat(gotty): support gotty v2

- internal/namespaces/iam/v1alpha1/custom.go
> feat(iam): add color for logs action

- cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-instance-delete-usage.golden
- docs/commands/rdb.md
- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_instance.go
- internal/namespaces/rdb/v1/custom_instance_test.go
- internal/namespaces/rdb/v1/testdata/test-create-instance-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-create-instance-simple.golden
- internal/namespaces/rdb/v1/testdata/test-create-instance-with-ipam-private-endpoint.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-create-instance-with-ipam-private-endpoint.golden
- internal/namespaces/rdb/v1/testdata/test-create-instance-with-password-generator.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-create-instance-with-static-private-endpoint.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-create-instance-with-static-private-endpoint.golden
> feat(rdb): ipam config for private endpoints

- docs/docker.md
> docs(docker): example for ssh-key usage

- cmd/scw/testdata/test-all-usage-rdb-acl-edit-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-acl-usage.golden
- docs/commands/rdb.md
- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_acl.go
> feat(rdb): add a command to edit ACL

- cmd/scw/testdata/test-all-usage-rdb-database-get-url-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-database-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-user-get-url-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-user-usage.golden
- docs/commands/rdb.md
- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_url.go
- internal/namespaces/rdb/v1/custom_url_test.go
- internal/namespaces/rdb/v1/custom_user.go
- internal/namespaces/rdb/v1/testdata/test-database-get-url-postgres.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-database-get-url-postgres.golden
- internal/namespaces/rdb/v1/testdata/test-user-get-url-my-sql.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-user-get-url-my-sql.golden
- internal/namespaces/rdb/v1/testdata/test-user-get-url-postgres.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-user-get-url-postgres.golden
- internal/namespaces/rdb/v1/testdata/test-user-get-url-with-custom-database.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-user-get-url-with-custom-database.golden
- internal/namespaces/rdb/v1/testdata/test-user-get-url-with-custom-user.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-user-get-url-with-custom-user.golden
> feat(rdb): generate connection url

- README.md
https://formulae.brew.sh/formula/scw
```release-note
docs(brew): mention linux support for homebrew installation
```
> docs(brew): mention linux support for homebrew installation

- cmd/scw/testdata/test-all-usage-rdb-acl-add-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-acl-delete-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-acl-edit-usage.golden
- cmd/scw/testdata/test-all-usage-rdb-acl-set-usage.golden
- docs/commands/rdb.md
- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_acl.go
- internal/namespaces/rdb/v1/custom_acl_test.go
- internal/namespaces/rdb/v1/testdata/test-add-acl-allow.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-add-acl-allow.golden
- internal/namespaces/rdb/v1/testdata/test-add-acl-multiple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-add-acl-multiple.golden
- internal/namespaces/rdb/v1/testdata/test-add-acl-remove-allowed-when-not-set.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-add-acl-remove-allowed-when-not-set.golden
- internal/namespaces/rdb/v1/testdata/test-add-acl-remove-allowed-when-set.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-add-acl-remove-allowed-when-set.golden
- internal/namespaces/rdb/v1/testdata/test-add-acl-simple.golden
- internal/namespaces/rdb/v1/testdata/test-delete-acl-multiple-when-not-set.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-delete-acl-multiple-when-not-set.golden
- internal/namespaces/rdb/v1/testdata/test-delete-acl-multiple-when-set.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-delete-acl-multiple-when-set.golden
- internal/namespaces/rdb/v1/testdata/test-delete-acl-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-delete-acl-simple.golden
- internal/namespaces/rdb/v1/testdata/test-set-acl-multiple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-set-acl-multiple.golden
- internal/namespaces/rdb/v1/testdata/test-set-acl-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-set-acl-simple.golden
> feat(rdb): acl simplified

- internal/namespaces/k8s/v1/custom.go
- internal/namespaces/k8s/v1/custom_cluster.go
> fix(k8s): better rendering of list-available-types for cluster resource

- internal/human/marshal_func.go
- internal/namespaces/redis/v1/custom.go
- internal/namespaces/redis/v1/custom_cluster.go
- internal/namespaces/redis/v1/testdata/test-endpoints-single-public-endpoint.golden
- internal/namespaces/redis/v1/testdata/test-endpoints-single-static-private-endpoint.golden
- internal/namespaces/redis/v1/testdata/test-endpoints-two-static-private-endpoints.golden
- internal/namespaces/redis/v1/testdata/test-ipam-config-both-ipam-and-static-private-endpoints.golden
- internal/namespaces/redis/v1/testdata/test-ipam-config-single-ipam-private-endpoint.golden
- internal/namespaces/redis/v1/testdata/test-ipam-config-two-ipam-private-endpoints.golden
> fix(redis): add better rendering redis-cluster-acl-rules-endpoints

- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_backup.go
- internal/namespaces/rdb/v1/rdb_cli.go
- internal/namespaces/rdb/v1/testdata/test-create-backup-simple.golden
- internal/namespaces/rdb/v1/testdata/test-export-backup-simple.golden
- internal/namespaces/rdb/v1/testdata/test-restore-backup-simple.golden
> fix(rdb): hide download url rdb backup list

- internal/namespaces/vpc/v2/custom_private_network.go
- internal/namespaces/vpc/v2/testdata/test-get-private-network-multiple.golden
- internal/namespaces/vpc/v2/testdata/test-get-private-network-simple.golden
> fix(vpc): add better vizualisation for private network subnets

- cmd/scw/testdata/test-all-usage-vpc-gw-gateway-create-usage.golden
- internal/namespaces/vpcgw/v1/custom.go
- internal/namespaces/vpcgw/v1/custom_gateway.go
> fix(vpc-gw): add wait option for vpc-gw create

- cmd/scw/testdata/test-all-usage-vpc-gw-gateway-network-create-usage.golden
- internal/namespaces/vpcgw/v1/custom.go
- internal/namespaces/vpcgw/v1/custom_gateway_network.go
> feat(vpc-gw): add --wait vpcGwGatewayNetworkCreate

- cmd/scw/testdata/test-all-usage-rdb-log-prepare-usage.golden
- go.mod
- go.sum
- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_log.go
> feat(rdb): add --wait prepareInstanceLogs

- internal/namespaces/vpcgw/v1/custom.go
- internal/namespaces/vpcgw/v1/custom_gateway_network.go
- internal/namespaces/vpcgw/v1/custom_gateway_network_test.go
- internal/namespaces/vpcgw/v1/testdata/test-list-gateway-type-simple.cassette.yaml
- internal/namespaces/vpcgw/v1/testdata/test-vpc-gw-gateway-get-simple.cassette.yaml
- internal/namespaces/vpcgw/v1/testdata/test-vpc-gw-gateway-get-simple.golden
- internal/testhelpers/helpers_vpc.go
- internal/testhelpers/helpers_vpcgw.go
> fix(vpcgw):add better vizualisation for gateway and IP

- .github/workflows/announce.yml
- .github/workflows/coverage.yml
> chore: rename github workflows

- internal/namespaces/init/prompt.go
> feat(init): consider secret-key as sensitive in prompt

- README.md
> docs(ipam): add in readme

- internal/namespaces/vpcgw/v1/custom.go
- internal/namespaces/vpcgw/v1/custom_gateway.go
- internal/namespaces/vpcgw/v1/custom_gateway_network.go
- internal/namespaces/vpcgw/v1/custom_gateway_test.go
- internal/namespaces/vpcgw/v1/testdata/test-list-gateway-type-simple.cassette.yaml
- internal/namespaces/vpcgw/v1/testdata/test-vpc-gw-gateway-get-simple.cassette.yaml
- internal/namespaces/vpcgw/v1/testdata/test-vpc-gw-gateway-get-simple.golden
- internal/namespaces/vpcgw/v1/testdata/test-vpc-gw-gateway-network-get-simple.cassette.yaml
- internal/namespaces/vpcgw/v1/testdata/test-vpc-gw-gateway-network-get-simple.golden
- internal/testhelpers/helpers_vpcgw.go
> fix(vpcgw):better vizualisation gw network dhcp

- cmd/scw/testdata/test-all-usage-baremetal-offer-get-usage#01.golden
- internal/namespaces/baremetal/v1/custom.go
- internal/namespaces/baremetal/v1/custom_offer.go
- internal/namespaces/baremetal/v1/custom_offer_test.go
- internal/namespaces/baremetal/v1/testdata/test-baremetal-get-offer-simple.cassette.yaml
- internal/namespaces/baremetal/v1/testdata/test-baremetal-get-offer-simple.golden
> fix(baremetal): better rendering get offer

- internal/core/bootstrap_test.go
- internal/e2e/errors_test.go
- internal/e2e/human_test.go
- internal/e2e/sdk_errors_test.go
Test API is currently unavailable
> tests(e2e): skip tests using test api

- internal/namespaces/rdb/v1/custom.go
- internal/namespaces/rdb/v1/custom_backup.go
- internal/namespaces/rdb/v1/testdata/test-create-backup-simple.golden
- internal/namespaces/rdb/v1/testdata/test-export-backup-simple.golden
- internal/namespaces/rdb/v1/testdata/test-list-backup-simple.golden
- internal/namespaces/rdb/v1/testdata/test-restore-backup-simple.golden
> fix(rdb):add download url backup get

- internal/namespaces/redis/v1/custom.go
- internal/namespaces/redis/v1/custom_cluster.go
> feat(rdb) : add autocompletion for node-type in migrate cluster

- .github/workflows/wasm.yml
- go.mod
- internal/wasm/roundtrip.go
- internal/wasm/run.go
- wasm/package.json
- wasm/wasm_exec.cjs
- wasm/wasm_exec_node.cjs
> feat(wasm): bump go to 1.21

- internal/namespaces/redis/v1/custom.go
- internal/namespaces/redis/v1/custom_cluster.go
```release-note
```
close #2958
> feat(redis): add autocompletion for setting name

- internal/namespaces/mnq/v1beta1/custom.go
- internal/namespaces/mnq/v1beta1/custom_nats.go
- internal/namespaces/mnq/v1beta1/custom_sns.go
- internal/namespaces/mnq/v1beta1/custom_sqs.go
```release-note
```
close #2897
> feat(mnq) : add autocompletion for credentials and account

- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yaml
- go.mod
> chore: bump go to 1.21

- .github/workflows/release.yml
- wasm/package.json
> ci(wasm): publish

- README.md
- docs/CONTINUOUS_CODE_DEPLOYMENT.md
- internal/namespaces/instance/v1/helpers_test.go
- internal/qa/qa.go
- scripts/README.md
> docs: update developers website url

- .github/dependabot.yml
> chore: add support for docker in dependabot

- cmd/scw/testdata/test-all-usage-iam-rule-create-usage.golden
- cmd/scw/testdata/test-all-usage-iam-rule-delete-usage.golden
- cmd/scw/testdata/test-all-usage-iam-rule-usage.golden
- docs/commands/iam.md
- internal/core/testing.go
- internal/namespaces/iam/v1alpha1/custom.go
- internal/namespaces/iam/v1alpha1/custom_policy.go
- internal/namespaces/iam/v1alpha1/custom_policy_test.go
- internal/namespaces/iam/v1alpha1/custom_rule.go
- internal/namespaces/iam/v1alpha1/custom_rule_test.go
- internal/namespaces/iam/v1alpha1/testdata/test-create-rule-simple.cassette.yaml
- internal/namespaces/iam/v1alpha1/testdata/test-create-rule-simple.golden
- internal/namespaces/iam/v1alpha1/testdata/test-delete-rule-simple.cassette.yaml
- internal/namespaces/iam/v1alpha1/testdata/test-delete-rule-simple.golden
- internal/namespaces/iam/v1alpha1/testdata/test-get-policy-with-rules-simple.cassette.yaml
- internal/namespaces/iam/v1alpha1/testdata/test-get-policy-with-rules-simple.golden
> feat(iam): improve rules handling

- cmd/scw/testdata/test-all-usage-sdb-sql-backup-list-usage.golden
- docs/commands/sdb-sql.md
- internal/namespaces/serverless_sqldb/v1alpha1/serverless_sqldb_cli.go
manual push of a missing generation PR.
> feat(serverless_sqldb): swap values of OrderBy of list database

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_server_create.go
> chore: bump scaleway sdk-go

- .golangci.yml
> chore(instance): fix linter for deprecated fields

- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yaml
- .github/workflows/wasm.yml
- Dockerfile
- go.mod
- scripts/check-size.sh
> chore: migrate to go1.22 and define explicit toolchain

- internal/namespaces/applesilicon/v1alpha1/custom_server.go
> feat(apple-silicon): add autocomplete server type

- cmd/scw/testdata/test-all-usage-rdb-instance-create-usage.golden
- docs/commands/autocomplete.md
- docs/commands/rdb.md
- internal/core/validate.go
- internal/core/validate_test.go
- internal/namespaces/rdb/v1/custom_instance.go
> feat(core):handle oneof validation

- internal/namespaces/mnq/v1beta1/custom_nats_test.go
> tests(mnq): use tmp home dir in context tests

- internal/namespaces/instance/v1/helpers_types.go
> feat(instance): use API to complete instance type per zone

- cmd/scw/testdata/test-all-usage-instance-server-get-rdp-password-usage.golden
- cmd/scw/testdata/test-all-usage-instance-server-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom.go
- internal/namespaces/instance/v1/custom_server_rdp.go
> feat(instance): get rdp password and decrypt it

- .github/CODEOWNERS
> chore: add support for CODEOWNERS

- cmd/scw/testdata/test-all-usage-instance-security-group-update-rule-usage.golden
- cmd/scw/testdata/test-all-usage-instance-server-action-usage.golden
- cmd/scw/testdata/test-all-usage-instance-server-enable-routed-ip-usage.golden
- cmd/scw/testdata/test-all-usage-instance-server-get-rdp-password-usage.golden
- cmd/scw/testdata/test-all-usage-instance-volume-wait-usage.golden
> chore: fix ci

- internal/namespaces/inference/v1beta1/custom_deployment_test.go
> fix(inference): skip test out of stock

- scripts/check-size.sh
> fix(script): increase binary size

- .github/workflows/release.yml
- .goreleaser.yml
> ci: fix goreleaser v2

- internal/namespaces/inference/v1beta1/custom_deployment.go
- internal/namespaces/inference/v1beta1/custom_deployment_test.go
- internal/namespaces/inference/v1beta1/testdata/test-deployment-create-deployment-with-wait-flag.cassette.yaml
- internal/namespaces/inference/v1beta1/testdata/test-deployment-create-deployment-with-wait-flag.golden
- internal/namespaces/inference/v1beta1/testdata/test-deployment-create-simple-deployment.cassette.yaml
- internal/namespaces/inference/v1beta1/testdata/test-deployment-create-simple-deployment.golden
> feat(inference): add test and increase timeout deployment

- internal/namespaces/marketplace/v2/custom_marshal.go
> fix(marketplace): return id in image get command

- internal/core/testing.go
- internal/namespaces/object/v1/custom_bucket_test.go
- internal/namespaces/object/v1/testdata/test-bucket-create-simple.golden
- internal/namespaces/object/v1/testdata/test-bucket-create-with-acl.golden
- internal/namespaces/object/v1/testdata/test-bucket-create-with-tags.golden
- internal/namespaces/object/v1/testdata/test-bucket-create-with-versioning.golden
- internal/namespaces/object/v1/testdata/test-bucket-get-simple.golden
- internal/namespaces/object/v1/testdata/test-bucket-get-with-size.golden
- internal/namespaces/object/v1/testdata/test-bucket-update-all-options.golden
- internal/namespaces/object/v1/testdata/test-bucket-update-tags.golden
> fix(test): delete suffix golden

- internal/namespaces/instance/v1/custom_server_create_builder.go
- internal/namespaces/instance/v1/testdata/test-create-server-errors-error-invalid-image-label.cassette.yaml
> refactor(instance): get server type when loading commercialType

- cmd/scw/testdata/test-all-usage-instance-snapshot-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/instance_cli.go
Should have been made by scaleway-bot. Extracted from #3983
> docs(instance): fix typo in snapshot doc

- .golangci.yml
> chore: define explicit enable/disable for linters

- .golangci.yml
> chore: add support for gomodguard

- .golangci.yml
> chore: add support for importas

- .golangci.yml
- internal/gofields/gofields_test.go
> chore: add support for gofmt

- .golangci.yml
- internal/args/args.go
- internal/args/marshal.go
- internal/args/unmarshal.go
- internal/core/autocomplete_utils.go
- internal/core/printer.go
- internal/core/reflect.go
- internal/e2e/sdk_errors_test.go
- internal/editor/reflect.go
- internal/gofields/gofields.go
- internal/human/marshal.go
- internal/interactive/print.go
- internal/namespaces/config/commands.go
- internal/passwordgenerator/password_generator.go
- internal/tabwriter/tabwriter_test.go
> chore: add support for intrange

- .golangci.yml
> chore: add support for usestdlibvars

- internal/sentry/sentry.go
> fix: update sentry url

- internal/namespaces/rdb/v1/custom_instance.go
```release-note
```
close : [#4075](https://github.com/scaleway/scaleway-cli/issues/4075)
> fix(rdb): fix custom type in rdb instance engine

- cmd/scw/testdata/test-all-usage-vpc-usage.golden
- docs/commands/vpc.md
- internal/namespaces/vpc/v2/custom.go
> fix(vpc): re-enable route

- .golangci.yml
- internal/config/config.go
> chore: add support for tagalign

- cmd/scw/testdata/test-all-usage-instance-snapshot-apply-migration-usage.golden
- cmd/scw/testdata/test-all-usage-instance-snapshot-plan-migration-usage.golden
- cmd/scw/testdata/test-all-usage-instance-snapshot-usage.golden
- docs/commands/instance.md
- internal/namespaces/instance/v1/custom.go
- internal/namespaces/instance/v1/custom_snapshot.go
- internal/namespaces/instance/v1/custom_volume.go
> feat(instance): duplicate volume migration for snapshot 

- internal/namespaces/instance/v1/custom_server.go
- internal/namespaces/instance/v1/custom_server_action_test.go
- internal/namespaces/instance/v1/custom_server_create_builder.go
> chore(instance): ignore routed-ip-enabled depreciation

- README.md
> doc: add serverless jobs to Reference documentation

- go.mod
- go.sum
- internal/namespaces/instance/v1/custom_server_create_builder.go
> fix(instance): optional image field

- internal/namespaces/instance/v1/custom_server.go
- internal/namespaces/instance/v1/custom_server_test.go
- internal/namespaces/instance/v1/testdata/test-create-server-ips-with-ipv6-and-dynamic-ip.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-create-server-ips-with-ipv6-and-ipv4.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-delete-with-multiple-ips.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-delete-with-multiple-ips.golden
> fix(instance): delete server with multiple IPs

- .github/workflows/nightly.yml
> ci: add CLI_UPDATE_GOLDENS: true flag

- .github/workflows/nightly.yml
> ci: fix serverless_sqldb package name

- internal/namespaces/instance/v1/custom_ssh_config_test.go
- internal/namespaces/instance/v1/testdata/test-ssh-config-install-install-config-and-create-default.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-ssh-config-install-install-config-and-include.cassette.yaml
I made some change in another PR to avoid creating IPs with servers in tests. This broke ssh config tests.
> test(instance): fix ssh config install tests

- internal/namespaces/instance/v1/custom_server_ssh_test.go
- internal/namespaces/instance/v1/testdata/test-server-ssh-simple.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-ssh-stopped-server.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-ssh-stopped-server.golden
- internal/namespaces/instance/v1/testdata/test-server-ssh-with-exit-code.cassette.yaml
> test(instance): fix server ssh tests

- .github/workflows/nightly.yml
- cmd/scw-sweeper/main.go
> ci: fix sweeper path

- .github/workflows/nightly.yml
> ci: add the sweeper in a different job

- go.mod
- go.sum
> chore: update golang.org/x/net

- internal/tabwriter/tabwriter_test.go
> fix(tabwriter): update for loop

- internal/namespaces/rdb/v1/testdata/test-list-backup-simple.cassette.yaml
- internal/namespaces/rdb/v1/testdata/test-list-backup-simple.golden
> ci : update cassette and goldens for test backup simple

- internal/namespaces/instance/v1/custom_server_action_test.go
- internal/namespaces/instance/v1/testdata/test-server-terminate-with-ip.cassette.yaml
- internal/namespaces/instance/v1/testdata/test-server-terminate-with-ip.golden
> test(instance): server terminate with ip check PermissionsDenied

- cmd/scw/testdata/test-all-usage-apple-silicon-private-network-add-usage.golden
- cmd/scw/testdata/test-all-usage-apple-silicon-private-network-delete-usage.golden
- cmd/scw/testdata/test-all-usage-apple-silicon-private-network-list-usage.golden
- cmd/scw/testdata/test-all-usage-apple-silicon-private-network-set-usage.golden
- cmd/scw/testdata/test-all-usage-apple-silicon-private-network-usage.golden
- cmd/scw/testdata/test-all-usage-apple-silicon-usage.golden
- docs/commands/apple-silicon.md
- go.mod
- go.sum
- internal/namespaces/applesilicon/v1alpha1/applesilicon_cli.go
> feat(applesilicon): add support for vpc

- .github/workflows/purge.yml
> ci: add support for a manual purge

- cmd/scw-sweeper/main.go
- go.mod
- go.sum
> chore(sweepers): fix webhosting

- .github/workflows/actionlint.yml
- .github/workflows/announce.yml
- .github/workflows/deploy-docs.yml
> ci: add support for actionlint

- .github/workflows/nightly.yml
> ci: add a ping when sweepers are failing

- .github/workflows/deploy-docs.yml
Added sudo for apt commands.
```release-note
```
> fix(docs): update doc build workflow

- go.mod
- go.sum
- internal/namespaces/lb/v1/testdata/test-list-lb-private-network-simple.cassette.yaml
- internal/namespaces/vpc/v2/testdata/test-get-private-network-multiple.cassette.yaml
> chore(lb): update cassette on attach/detach private network

- go.mod
Explicitly set go minor version
```release-note
```
> fix(go.mod): set go minor version

- internal/namespaces/jobs/v1alpha1/custom_job_definition.go
Fixes https://github.com/scaleway/scaleway-cli/issues/4637
```shell
scw jobs definition start -w c5850ba1-b7ae-4cc0-b4b9-619f40dedfb6 -w d97d9e78-90c8-4289-a1a1-738ee42a71d5
ID                    f3948988-9110-44f7-8726-eb1a761b20eb …
```
> fix(jobs): panic when starting a job with --wait

- cmd/scw/testdata/test-all-usage-help-output-usage.golden
- core/printer.go
- docs/commands/autocomplete.md
- docs/commands/help.md
- internal/namespaces/help/output.go
fixes https://github.com/scaleway/scaleway-cli/issues/3117
```
scw secret version access ac733d5a-1d83-4148-b4fe-cc0499ff492c revision=1 -o template="{{  json .Data }}"
"eW91cl9zZWNyZXQ="
```
> feat(printer): add a json function in the template printer

- core/command_interceptor.go
```release-note
- fix quota exceeded error to show "current/quota" instead of duplicated values
```
> fix(core): add quota in quotas exceeded error

- .github/workflows/release.yml
- .github/workflows/unit-tests.yaml
> ci: add go mod tidy verification step

- cmd/scw-sweeper/main.go
> tests: put ipam sweeper last

- core/human/marshal_test.go
> chore: fix marshall test

- internal/namespaces/function/v1beta1/custom_deploy_test.go
- internal/namespaces/function/v1beta1/testdata/test-deploy-simple.cassette.yaml
- internal/namespaces/function/v1beta1/testdata/test-deploy-simple.golden
> fix(function): update go runtime

- docs/commands/index.md
- docs/mkdocs.yml
- Updated menu according to new categories
- Fixed image broken link in index
- removed useless/placeholder conf
```release-note
none
```
> docs: fix broken image and update navigation

- internal/namespaces/rdb/v1/custom_instance.go
```release-note
```
close #4833
> fix(rdb): handle pointer type in instance create engine autocomplete

- wasm/package.json
- wasm/pnpm-lock.yaml
> chore: bump wasm dependencies

- internal/namespaces/redis/v1/custom_cluster.go
- internal/namespaces/redis/v1/testdata/test-ipam-config-single-ipam-private-endpoint.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-ipam-config-single-ipam-private-endpoint.golden
- internal/namespaces/redis/v1/testdata/test-ipam-config-two-ipam-private-endpoints.cassette.yaml
- internal/namespaces/redis/v1/testdata/test-ipam-config-two-ipam-private-endpoints.golden
> fix(redis): nightly ipam test

- internal/platform/terminal/terminal_client.go
> chore: fix a typo in help message

- cmd/scw/testdata/test-all-usage-lb-frontend-create-usage.golden
- cmd/scw/testdata/test-all-usage-lb-frontend-update-usage.golden
- docs/commands/lb.md
- internal/namespaces/lb/v1/lb_cli.go
> feat(lb): add access_logs field to frontend

- .github/workflows/nightly.yml
- .github/workflows/unit-tests.yaml
- go.mod
- go.sum
> ci: add support for gotestsum
